#!/usr/bin/env bash
set -e -u -o pipefail
#set -x

function main() {
    this_script_dir="$(dirname "${BASH_SOURCE[0]}")"
    this_script_dir="$(realpath "${this_script_dir}")"
    src_repo_root_dir="$(realpath "${this_script_dir}/../..")"

    source "${src_repo_root_dir}/tools/shared.sh"

    # The script below must be called before any .php scripts in ./tools/build/
    # because .php scripts in ./tools/build/ depend on some of .php source files
    # generated by the script below
    "${src_repo_root_dir}/tools/build/configure_php_templates_if_not_done_yet.sh"

    php "${src_repo_root_dir}/tools/build/verify_generated_composer_lock_files.php"

    php "${src_repo_root_dir}/tools/test/static_check_prod.php"
}

main "$@"
