#!/usr/bin/env bash
set -e -o pipefail
#set -x

show_help() {
    echo "Usage: $0 --php_versions <versions>"
    echo
    echo "Arguments:"
    echo "  --php_versions      Required. List of PHP versions separated by spaces (e.g., '81 82 83 84')."
    echo "  --logs_dir          Required. Full path to the directory where generated logs will be stored. NOTE: All existing files in this directory will be deleted"
    echo
    echo "Example:"
    echo "  $0 --php_versions '81 82 83 84' --logs_dir '/directory/to/store/logs'"
}

# Function to parse arguments
parse_args() {
    echo "arguments: $*"

    PHP_versions_no_dot=""
    logs_dir=""

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            --php_versions)
                # SC2206: Quote to prevent word splitting/globbing, or split robustly with mapfile or read -a.
                # shellcheck disable=SC2206
                PHP_versions_no_dot=($2)
                shift
                ;;
            --logs_dir)
                logs_dir="$2"
                shift
                ;;
            --help)
                show_help
                exit 0
                ;;
            *)
                echo "Unknown parameter passed: $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done

    if [ -z "${PHP_versions_no_dot[*]}" ] ; then
        echo "<php_versions> argument is missing"
        show_help
        exit 1
    fi
    if [ -z "${logs_dir}" ] ; then
        echo "<logs_dir> argument is missing"
        show_help
        exit 1
    fi

    echo "PHP_versions_no_dot: ${PHP_versions_no_dot[*]}"
    echo "logs_dir: ${logs_dir}"
}

main() {
    this_script_dir="$(dirname "${BASH_SOURCE[0]}")"
    this_script_dir="$(realpath "${this_script_dir}")"
    echo "Entered ${BASH_SOURCE[0]}"

    repo_root_dir="$(realpath "${PWD}")"
    source "${repo_root_dir}/tools/shared.sh"

    parse_args "$@"

    ensure_dir_exists_and_empty "${logs_dir}"
    touch "${logs_dir}/z_dummy_file_to_make_directory_non-empty"

    # ./tools/build/configure_php_templates.sh must be called before any .php scripts in ./tools/build/
    # because .php scripts in ./tools/build/ depend on some of .php source files
    # generated by ./tools/build/configure_php_templates.sh
    ./tools/build/configure_php_templates.sh

    php ./tools/build/verify_generated_composer_lock_files.php

    # SC2034: <env var> appears unused. Verify use (or export if used externally).
    # shellcheck disable=SC2034
    ELASTIC_OTEL_PHP_TESTS_LOGS_DIRECTORY="/elastic_otel_php_tests/logs"
    local docker_run_env_vars_cmd_line_args=()
    build_docker_env_vars_command_line_part docker_run_env_vars_cmd_line_args

    for PHP_version_no_dot in "${PHP_versions_no_dot[@]}"; do
        local PHP_docker_image
        PHP_docker_image=$(build_light_PHP_docker_image_name_for_version_no_dot "${PHP_version_no_dot}")

        # To run static check on prod (without dev only dependencies)
        local PhpStan_neon_bootstrapFiles_value_line_original="- ./tests/bootstrap.php"
        local PhpStan_neon_bootstrapFiles_value_line_for_prod="- ./tests/bootstrapProdStaticCheck.php"
        local PhpStan_neon_bootstrapFiles_value_line_original_escaped="${PhpStan_neon_bootstrapFiles_value_line_original//\//\\\/}"
        local PhpStan_neon_bootstrapFiles_value_line_for_prod_escaped="${PhpStan_neon_bootstrapFiles_value_line_for_prod//\//\\\/}"
        local replace_PhpStan_neon_bootstrapFiles_for_prod="sed -i 's/${PhpStan_neon_bootstrapFiles_value_line_original_escaped}/${PhpStan_neon_bootstrapFiles_value_line_for_prod_escaped}/g'"
        docker run --rm \
            "${docker_run_env_vars_cmd_line_args[@]}" \
            -v "${PWD}/:/repo_root/:ro" \
            -v "${logs_dir}:/elastic_otel_php_tests/logs" \
            -w "/repo_root" \
            "${PHP_docker_image}" \
            sh -c "\
                apk update && apk add bash git \
                && curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin \
                && echo 'Running static check on prod (without dev only dependencies); PHP_version_no_dot:' ${PHP_version_no_dot} \
                && mkdir -p /tmp/repo \
                && cp -r /repo_root/* /tmp/repo/ \
                && rm -rf /tmp/repo/composer.json /tmp/repo/composer.lock /tmp/repo/vendor/ /tmp/repo/prod/php/vendor_* \
                && mv /tmp/repo/tests /tmp/repo/tests_original \
                && mkdir /tmp/repo/tests \
                && mv /tmp/repo/tests_original/elastic_otel_extension_stubs /tmp/repo/tests/elastic_otel_extension_stubs \
                && mv /tmp/repo/tests_original/bootstrapProdStaticCheck.php /tmp/repo/tests/bootstrapProdStaticCheck.php \
                && rm -rf /tmp/repo/tests_original/ \
                && ${replace_PhpStan_neon_bootstrapFiles_for_prod} /tmp/repo/phpstan.dist.neon \
                && cd /tmp/repo/ \
                && php ./tools/build/select_json_lock_and_install_PHP_deps.php prod_static_check \
                && composer run-script -- static_check \
                && echo 'Running static check and unit tests; PHP_version_no_dot:' ${PHP_version_no_dot} \
                && cd / && rm -rf /tmp/repo/ \
                && mkdir -p /tmp/repo \
                && cp -r /repo_root/* /tmp/repo/ \
                && rm -rf /tmp/repo/composer.json /tmp/repo/composer.lock /tmp/repo/vendor/ /tmp/repo/prod/php/vendor_* \
                && cd /tmp/repo/ \
                && php ./tools/build/select_json_lock_and_install_PHP_deps.php test \
                && composer run-script -- static_check_and_run_unit_tests \
            "
    done

    echo "Exiting ${BASH_SOURCE[0]}"
}

main "$@"
