#!/usr/bin/env bash
set -e -o pipefail
#set -x

show_help() {
    echo "Usage: $0 --php_versions <versions>"
    echo
    echo "Arguments:"
    echo "  --php_versions           Required. List of PHP versions separated by spaces (e.g., '81 82 83 84')."
    echo
    echo "Example:"
    echo "  $0 --php_versions '81 82 83 84'"
}

# Function to parse arguments
parse_args() {
    while [[ "$#" -gt 0 ]]; do
        case $1 in
            --php_versions)
                # SC2206: Quote to prevent word splitting/globbing, or split robustly with mapfile or read -a.
                # shellcheck disable=SC2206
                PHP_versions_no_dot=($2)
                shift
                ;;
            --help)
                show_help
                exit 0
                ;;
            *)
                echo "Unknown parameter passed: $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done
}

main() {
    this_script_dir="$(dirname "${BASH_SOURCE[0]}")"
    this_script_dir="$(realpath "${this_script_dir}")"

    repo_root_dir="$(realpath "${PWD}")"
    source "${repo_root_dir}/tools/shared.sh"

    parse_args "$@"

    # SC2128: Expanding an array without an index only gives the first element.
    # shellcheck disable=SC2128
    if [[ -z "$PHP_versions_no_dot" ]]; then
        echo "Error: Missing required arguments."
        show_help
        exit 1
    fi

    # ./tools/build/configure_php_templates.sh must be called before any .php scripts in ./tools/build/
    # because .php scripts in ./tools/build/ depend on some of .php source files
    # generated by ./tools/build/configure_php_templates.sh
    ./tools/build/configure_php_templates.sh

    php ./tools/build/verify_generated_composer_lock_files.php

    local env_kind="prod"

    for PHP_version_no_dot in "${PHP_versions_no_dot[@]}"; do

        local composer_json_file_name
        composer_json_file_name="$(build_generated_composer_json_file_name "${env_kind}")"
        local composer_json_full_path="${repo_root_dir:?}/${elastic_otel_php_build_tools_composer_lock_files_dir_name:?}/${composer_json_file_name}"

        local composer_lock_file_name
        composer_lock_file_name="$(build_generated_composer_lock_file_name "${env_kind}" "${PHP_version_no_dot}")"
        local composer_lock_full_path="${repo_root_dir:?}/${elastic_otel_php_build_tools_composer_lock_files_dir_name:?}/${composer_lock_file_name}"

        local PHP_docker_image
        PHP_docker_image=$(build_light_PHP_docker_image_name_for_version_no_dot "${PHP_version_no_dot}")

        local volume_mount_opts
        build_container_volume_mount_options volume_mount_opts
        echo "volume_mount_opts: " "${volume_mount_opts[@]}"

        # shellcheck disable=SC2068
        docker run --rm \
            "${volume_mount_opts[@]}" \
            -v "${composer_json_full_path}:/repo_root/composer.json:ro" \
            -v "${composer_lock_full_path}:/repo_root/composer.lock:ro" \
            -w "/repo_root" \
            "${PHP_docker_image}" \
            sh -c "\
                apk update && apk add bash git \
                && curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin \
                && echo \"ls -l .\" && ls -l . \
                && ls -l ${elastic_otel_php_files_to_mount_in_container[*]:?} ${elastic_otel_php_dirs_to_mount_in_container[*]:?} \
                && php ./tools/build/install_php_deps_in_test_env.php \
                && composer run-script -- static_check_and_run_unit_tests \
            "
    done
}

main "$@"
