<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AgentDisconnect is the last message sent from the Agent to the Server. The Server
 * SHOULD forget the association of the Agent instance with the message stream.
 * If the message stream is closed in the transport layer then the Server SHOULD
 * forget association of all Agent instances that were previously established for
 * this message stream using AgentConnect message, even if the corresponding
 * AgentDisconnect message were not explicitly received from the Agent.
 *
 * Generated from protobuf message <code>opamp.proto.AgentDisconnect</code>
 */
class AgentDisconnect extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

}

