<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use UnexpectedValueException;

/**
 * Protobuf type <code>opamp.proto.AgentToServerFlags</code>
 */
class AgentToServerFlags
{
    /**
     * Generated from protobuf enum <code>AgentToServerFlags_Unspecified = 0;</code>
     */
    const AgentToServerFlags_Unspecified = 0;
    /**
     * The Agent requests Server go generate a new instance_uid, which will
     * be sent back in ServerToAgent message
     *
     * Generated from protobuf enum <code>AgentToServerFlags_RequestInstanceUid = 1;</code>
     */
    const AgentToServerFlags_RequestInstanceUid = 1;

    private static $valueToName = [
        self::AgentToServerFlags_Unspecified => 'AgentToServerFlags_Unspecified',
        self::AgentToServerFlags_RequestInstanceUid => 'AgentToServerFlags_RequestInstanceUid',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

