<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.AgentDescription</code>
 */
class AgentDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * Attributes that identify the Agent.
     * Keys/values are according to OpenTelemetry semantic conventions, see:
     * https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions
     * For standalone running Agents (such as OpenTelemetry Collector) the following
     * attributes SHOULD be specified:
     * - service.name should be set to a reverse FQDN that uniquely identifies the
     *   Agent type, e.g. "io.opentelemetry.collector"
     * - service.namespace if it is used in the environment where the Agent runs.
     * - service.version should be set to version number of the Agent build.
     * - service.instance.id should be set. It may be set equal to the Agent's
     *   instance uid (equal to ServerToAgent.instance_uid field) or any other value
     *   that uniquely identifies the Agent in combination with other attributes.
     * - any other attributes that are necessary for uniquely identifying the Agent's
     *   own telemetry.
     * The Agent SHOULD also include these attributes in the Resource of its own
     * telemetry. The combination of identifying attributes SHOULD be sufficient to
     * uniquely identify the Agent's own telemetry in the destination system to which
     * the Agent sends its own telemetry.
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue identifying_attributes = 1;</code>
     */
    private $identifying_attributes;
    /**
     * Attributes that do not necessarily identify the Agent but help describe
     * where it runs.
     * The following attributes SHOULD be included:
     * - os.type, os.version - to describe where the Agent runs.
     * - host.* to describe the host the Agent runs on.
     * - cloud.* to describe the cloud where the host is located.
     * - any other relevant Resource attributes that describe this Agent and the
     *   environment it runs in.
     * - any user-defined attributes that the end user would like to associate
     *   with this Agent.
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue non_identifying_attributes = 2;</code>
     */
    private $non_identifying_attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\ElasticOTelTests\Generated\OpampProto\KeyValue>|\Google\Protobuf\Internal\RepeatedField $identifying_attributes
     *           Attributes that identify the Agent.
     *           Keys/values are according to OpenTelemetry semantic conventions, see:
     *           https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions
     *           For standalone running Agents (such as OpenTelemetry Collector) the following
     *           attributes SHOULD be specified:
     *           - service.name should be set to a reverse FQDN that uniquely identifies the
     *             Agent type, e.g. "io.opentelemetry.collector"
     *           - service.namespace if it is used in the environment where the Agent runs.
     *           - service.version should be set to version number of the Agent build.
     *           - service.instance.id should be set. It may be set equal to the Agent's
     *             instance uid (equal to ServerToAgent.instance_uid field) or any other value
     *             that uniquely identifies the Agent in combination with other attributes.
     *           - any other attributes that are necessary for uniquely identifying the Agent's
     *             own telemetry.
     *           The Agent SHOULD also include these attributes in the Resource of its own
     *           telemetry. The combination of identifying attributes SHOULD be sufficient to
     *           uniquely identify the Agent's own telemetry in the destination system to which
     *           the Agent sends its own telemetry.
     *     @type array<\ElasticOTelTests\Generated\OpampProto\KeyValue>|\Google\Protobuf\Internal\RepeatedField $non_identifying_attributes
     *           Attributes that do not necessarily identify the Agent but help describe
     *           where it runs.
     *           The following attributes SHOULD be included:
     *           - os.type, os.version - to describe where the Agent runs.
     *           - host.* to describe the host the Agent runs on.
     *           - cloud.* to describe the cloud where the host is located.
     *           - any other relevant Resource attributes that describe this Agent and the
     *             environment it runs in.
     *           - any user-defined attributes that the end user would like to associate
     *             with this Agent.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Attributes that identify the Agent.
     * Keys/values are according to OpenTelemetry semantic conventions, see:
     * https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions
     * For standalone running Agents (such as OpenTelemetry Collector) the following
     * attributes SHOULD be specified:
     * - service.name should be set to a reverse FQDN that uniquely identifies the
     *   Agent type, e.g. "io.opentelemetry.collector"
     * - service.namespace if it is used in the environment where the Agent runs.
     * - service.version should be set to version number of the Agent build.
     * - service.instance.id should be set. It may be set equal to the Agent's
     *   instance uid (equal to ServerToAgent.instance_uid field) or any other value
     *   that uniquely identifies the Agent in combination with other attributes.
     * - any other attributes that are necessary for uniquely identifying the Agent's
     *   own telemetry.
     * The Agent SHOULD also include these attributes in the Resource of its own
     * telemetry. The combination of identifying attributes SHOULD be sufficient to
     * uniquely identify the Agent's own telemetry in the destination system to which
     * the Agent sends its own telemetry.
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue identifying_attributes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdentifyingAttributes()
    {
        return $this->identifying_attributes;
    }

    /**
     * Attributes that identify the Agent.
     * Keys/values are according to OpenTelemetry semantic conventions, see:
     * https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions
     * For standalone running Agents (such as OpenTelemetry Collector) the following
     * attributes SHOULD be specified:
     * - service.name should be set to a reverse FQDN that uniquely identifies the
     *   Agent type, e.g. "io.opentelemetry.collector"
     * - service.namespace if it is used in the environment where the Agent runs.
     * - service.version should be set to version number of the Agent build.
     * - service.instance.id should be set. It may be set equal to the Agent's
     *   instance uid (equal to ServerToAgent.instance_uid field) or any other value
     *   that uniquely identifies the Agent in combination with other attributes.
     * - any other attributes that are necessary for uniquely identifying the Agent's
     *   own telemetry.
     * The Agent SHOULD also include these attributes in the Resource of its own
     * telemetry. The combination of identifying attributes SHOULD be sufficient to
     * uniquely identify the Agent's own telemetry in the destination system to which
     * the Agent sends its own telemetry.
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue identifying_attributes = 1;</code>
     * @param array<\ElasticOTelTests\Generated\OpampProto\KeyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdentifyingAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ElasticOTelTests\Generated\OpampProto\KeyValue::class);
        $this->identifying_attributes = $arr;

        return $this;
    }

    /**
     * Attributes that do not necessarily identify the Agent but help describe
     * where it runs.
     * The following attributes SHOULD be included:
     * - os.type, os.version - to describe where the Agent runs.
     * - host.* to describe the host the Agent runs on.
     * - cloud.* to describe the cloud where the host is located.
     * - any other relevant Resource attributes that describe this Agent and the
     *   environment it runs in.
     * - any user-defined attributes that the end user would like to associate
     *   with this Agent.
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue non_identifying_attributes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNonIdentifyingAttributes()
    {
        return $this->non_identifying_attributes;
    }

    /**
     * Attributes that do not necessarily identify the Agent but help describe
     * where it runs.
     * The following attributes SHOULD be included:
     * - os.type, os.version - to describe where the Agent runs.
     * - host.* to describe the host the Agent runs on.
     * - cloud.* to describe the cloud where the host is located.
     * - any other relevant Resource attributes that describe this Agent and the
     *   environment it runs in.
     * - any user-defined attributes that the end user would like to associate
     *   with this Agent.
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue non_identifying_attributes = 2;</code>
     * @param array<\ElasticOTelTests\Generated\OpampProto\KeyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNonIdentifyingAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ElasticOTelTests\Generated\OpampProto\KeyValue::class);
        $this->non_identifying_attributes = $arr;

        return $this;
    }

}

