<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.AgentToServer</code>
 */
class AgentToServer extends \Google\Protobuf\Internal\Message
{
    /**
     * Globally unique identifier of the running instance of the Agent. SHOULD remain
     * unchanged for the lifetime of the Agent process.
     * MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *
     * Generated from protobuf field <code>bytes instance_uid = 1;</code>
     */
    protected $instance_uid = '';
    /**
     * The sequence number is incremented by 1 for every AgentToServer sent
     * by the Agent. This allows the Server to detect that it missed a message when
     * it notices that the sequence_num is not exactly by 1 greater than the previously
     * received one.
     *
     * Generated from protobuf field <code>uint64 sequence_num = 2;</code>
     */
    protected $sequence_num = 0;
    /**
     * Data that describes the Agent, its type, where it runs, etc.
     * May be omitted if nothing changed since last AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentDescription agent_description = 3;</code>
     */
    protected $agent_description = null;
    /**
     * Bitmask of flags defined by AgentCapabilities enum.
     * All bits that are not defined in AgentCapabilities enum MUST be set to 0 by
     * the Agent. This allows extending the protocol and the AgentCapabilities enum
     * in the future such that old Agents automatically report that they don't
     * support the new capability.
     * This field MUST be always set.
     *
     * Generated from protobuf field <code>uint64 capabilities = 4;</code>
     */
    protected $capabilities = 0;
    /**
     * The current health of the Agent and sub-components. The top-level ComponentHealth represents
     * the health of the Agent overall. May be omitted if nothing changed since last AgentToServer
     * message.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ComponentHealth health = 5;</code>
     */
    protected $health = null;
    /**
     * The current effective configuration of the Agent. The effective configuration is
     * the one that is currently used by the Agent. The effective configuration may be
     * different from the remote configuration received from the Server earlier, e.g.
     * because the Agent uses a local configuration instead (or in addition).
     * This field SHOULD be unset if the effective config is unchanged since the last
     * AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.EffectiveConfig effective_config = 6;</code>
     */
    protected $effective_config = null;
    /**
     * The status of the remote config that was previously received from the Server.
     * This field SHOULD be unset if the remote config status is unchanged since the
     * last AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.RemoteConfigStatus remote_config_status = 7;</code>
     */
    protected $remote_config_status = null;
    /**
     * The list of the Agent packages, including package statuses. This field SHOULD be
     * unset if this information is unchanged since the last AgentToServer message for
     * this Agent was sent in the stream.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.PackageStatuses package_statuses = 8;</code>
     */
    protected $package_statuses = null;
    /**
     * AgentDisconnect MUST be set in the last AgentToServer message sent from the
     * Agent to the Server.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentDisconnect agent_disconnect = 9;</code>
     */
    protected $agent_disconnect = null;
    /**
     * Bit flags as defined by AgentToServerFlags bit masks.
     *
     * Generated from protobuf field <code>uint64 flags = 10;</code>
     */
    protected $flags = 0;
    /**
     * A request to create connection settings. This field is set for flows where
     * the Agent initiates the creation of connection settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsRequest connection_settings_request = 11;</code>
     */
    protected $connection_settings_request = null;
    /**
     * A message indicating custom capabilities supported by the Agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomCapabilities custom_capabilities = 12;</code>
     */
    protected $custom_capabilities = null;
    /**
     * A custom message sent from an Agent to the Server.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomMessage custom_message = 13;</code>
     */
    protected $custom_message = null;
    /**
     * A message indicating the components that are available for configuration on the agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.AvailableComponents available_components = 14;</code>
     */
    protected $available_components = null;
    /**
     * The status of the OfferedConnectionSettings that was previously received
     * from the Server. This field SHOULD be unset if the offered connection
     * settings status is unchanged since the last AgentToServer message.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsStatus connection_settings_status = 15;</code>
     */
    protected $connection_settings_status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $instance_uid
     *           Globally unique identifier of the running instance of the Agent. SHOULD remain
     *           unchanged for the lifetime of the Agent process.
     *           MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *     @type int|string $sequence_num
     *           The sequence number is incremented by 1 for every AgentToServer sent
     *           by the Agent. This allows the Server to detect that it missed a message when
     *           it notices that the sequence_num is not exactly by 1 greater than the previously
     *           received one.
     *     @type \ElasticOTelTests\Generated\OpampProto\AgentDescription $agent_description
     *           Data that describes the Agent, its type, where it runs, etc.
     *           May be omitted if nothing changed since last AgentToServer message.
     *     @type int|string $capabilities
     *           Bitmask of flags defined by AgentCapabilities enum.
     *           All bits that are not defined in AgentCapabilities enum MUST be set to 0 by
     *           the Agent. This allows extending the protocol and the AgentCapabilities enum
     *           in the future such that old Agents automatically report that they don't
     *           support the new capability.
     *           This field MUST be always set.
     *     @type \ElasticOTelTests\Generated\OpampProto\ComponentHealth $health
     *           The current health of the Agent and sub-components. The top-level ComponentHealth represents
     *           the health of the Agent overall. May be omitted if nothing changed since last AgentToServer
     *           message.
     *           Status: [Beta]
     *     @type \ElasticOTelTests\Generated\OpampProto\EffectiveConfig $effective_config
     *           The current effective configuration of the Agent. The effective configuration is
     *           the one that is currently used by the Agent. The effective configuration may be
     *           different from the remote configuration received from the Server earlier, e.g.
     *           because the Agent uses a local configuration instead (or in addition).
     *           This field SHOULD be unset if the effective config is unchanged since the last
     *           AgentToServer message.
     *     @type \ElasticOTelTests\Generated\OpampProto\RemoteConfigStatus $remote_config_status
     *           The status of the remote config that was previously received from the Server.
     *           This field SHOULD be unset if the remote config status is unchanged since the
     *           last AgentToServer message.
     *     @type \ElasticOTelTests\Generated\OpampProto\PackageStatuses $package_statuses
     *           The list of the Agent packages, including package statuses. This field SHOULD be
     *           unset if this information is unchanged since the last AgentToServer message for
     *           this Agent was sent in the stream.
     *           Status: [Beta]
     *     @type \ElasticOTelTests\Generated\OpampProto\AgentDisconnect $agent_disconnect
     *           AgentDisconnect MUST be set in the last AgentToServer message sent from the
     *           Agent to the Server.
     *     @type int|string $flags
     *           Bit flags as defined by AgentToServerFlags bit masks.
     *     @type \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsRequest $connection_settings_request
     *           A request to create connection settings. This field is set for flows where
     *           the Agent initiates the creation of connection settings.
     *           Status: [Development]
     *     @type \ElasticOTelTests\Generated\OpampProto\CustomCapabilities $custom_capabilities
     *           A message indicating custom capabilities supported by the Agent.
     *           Status: [Development]
     *     @type \ElasticOTelTests\Generated\OpampProto\CustomMessage $custom_message
     *           A custom message sent from an Agent to the Server.
     *           Status: [Development]
     *     @type \ElasticOTelTests\Generated\OpampProto\AvailableComponents $available_components
     *           A message indicating the components that are available for configuration on the agent.
     *           Status: [Development]
     *     @type \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsStatus $connection_settings_status
     *           The status of the OfferedConnectionSettings that was previously received
     *           from the Server. This field SHOULD be unset if the offered connection
     *           settings status is unchanged since the last AgentToServer message.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Globally unique identifier of the running instance of the Agent. SHOULD remain
     * unchanged for the lifetime of the Agent process.
     * MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *
     * Generated from protobuf field <code>bytes instance_uid = 1;</code>
     * @return string
     */
    public function getInstanceUid()
    {
        return $this->instance_uid;
    }

    /**
     * Globally unique identifier of the running instance of the Agent. SHOULD remain
     * unchanged for the lifetime of the Agent process.
     * MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *
     * Generated from protobuf field <code>bytes instance_uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceUid($var)
    {
        GPBUtil::checkString($var, False);
        $this->instance_uid = $var;

        return $this;
    }

    /**
     * The sequence number is incremented by 1 for every AgentToServer sent
     * by the Agent. This allows the Server to detect that it missed a message when
     * it notices that the sequence_num is not exactly by 1 greater than the previously
     * received one.
     *
     * Generated from protobuf field <code>uint64 sequence_num = 2;</code>
     * @return int|string
     */
    public function getSequenceNum()
    {
        return $this->sequence_num;
    }

    /**
     * The sequence number is incremented by 1 for every AgentToServer sent
     * by the Agent. This allows the Server to detect that it missed a message when
     * it notices that the sequence_num is not exactly by 1 greater than the previously
     * received one.
     *
     * Generated from protobuf field <code>uint64 sequence_num = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequenceNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->sequence_num = $var;

        return $this;
    }

    /**
     * Data that describes the Agent, its type, where it runs, etc.
     * May be omitted if nothing changed since last AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentDescription agent_description = 3;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\AgentDescription|null
     */
    public function getAgentDescription()
    {
        return $this->agent_description;
    }

    public function hasAgentDescription()
    {
        return isset($this->agent_description);
    }

    public function clearAgentDescription()
    {
        unset($this->agent_description);
    }

    /**
     * Data that describes the Agent, its type, where it runs, etc.
     * May be omitted if nothing changed since last AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentDescription agent_description = 3;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\AgentDescription $var
     * @return $this
     */
    public function setAgentDescription($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\AgentDescription::class);
        $this->agent_description = $var;

        return $this;
    }

    /**
     * Bitmask of flags defined by AgentCapabilities enum.
     * All bits that are not defined in AgentCapabilities enum MUST be set to 0 by
     * the Agent. This allows extending the protocol and the AgentCapabilities enum
     * in the future such that old Agents automatically report that they don't
     * support the new capability.
     * This field MUST be always set.
     *
     * Generated from protobuf field <code>uint64 capabilities = 4;</code>
     * @return int|string
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * Bitmask of flags defined by AgentCapabilities enum.
     * All bits that are not defined in AgentCapabilities enum MUST be set to 0 by
     * the Agent. This allows extending the protocol and the AgentCapabilities enum
     * in the future such that old Agents automatically report that they don't
     * support the new capability.
     * This field MUST be always set.
     *
     * Generated from protobuf field <code>uint64 capabilities = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCapabilities($var)
    {
        GPBUtil::checkUint64($var);
        $this->capabilities = $var;

        return $this;
    }

    /**
     * The current health of the Agent and sub-components. The top-level ComponentHealth represents
     * the health of the Agent overall. May be omitted if nothing changed since last AgentToServer
     * message.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ComponentHealth health = 5;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\ComponentHealth|null
     */
    public function getHealth()
    {
        return $this->health;
    }

    public function hasHealth()
    {
        return isset($this->health);
    }

    public function clearHealth()
    {
        unset($this->health);
    }

    /**
     * The current health of the Agent and sub-components. The top-level ComponentHealth represents
     * the health of the Agent overall. May be omitted if nothing changed since last AgentToServer
     * message.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ComponentHealth health = 5;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\ComponentHealth $var
     * @return $this
     */
    public function setHealth($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\ComponentHealth::class);
        $this->health = $var;

        return $this;
    }

    /**
     * The current effective configuration of the Agent. The effective configuration is
     * the one that is currently used by the Agent. The effective configuration may be
     * different from the remote configuration received from the Server earlier, e.g.
     * because the Agent uses a local configuration instead (or in addition).
     * This field SHOULD be unset if the effective config is unchanged since the last
     * AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.EffectiveConfig effective_config = 6;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\EffectiveConfig|null
     */
    public function getEffectiveConfig()
    {
        return $this->effective_config;
    }

    public function hasEffectiveConfig()
    {
        return isset($this->effective_config);
    }

    public function clearEffectiveConfig()
    {
        unset($this->effective_config);
    }

    /**
     * The current effective configuration of the Agent. The effective configuration is
     * the one that is currently used by the Agent. The effective configuration may be
     * different from the remote configuration received from the Server earlier, e.g.
     * because the Agent uses a local configuration instead (or in addition).
     * This field SHOULD be unset if the effective config is unchanged since the last
     * AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.EffectiveConfig effective_config = 6;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\EffectiveConfig $var
     * @return $this
     */
    public function setEffectiveConfig($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\EffectiveConfig::class);
        $this->effective_config = $var;

        return $this;
    }

    /**
     * The status of the remote config that was previously received from the Server.
     * This field SHOULD be unset if the remote config status is unchanged since the
     * last AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.RemoteConfigStatus remote_config_status = 7;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\RemoteConfigStatus|null
     */
    public function getRemoteConfigStatus()
    {
        return $this->remote_config_status;
    }

    public function hasRemoteConfigStatus()
    {
        return isset($this->remote_config_status);
    }

    public function clearRemoteConfigStatus()
    {
        unset($this->remote_config_status);
    }

    /**
     * The status of the remote config that was previously received from the Server.
     * This field SHOULD be unset if the remote config status is unchanged since the
     * last AgentToServer message.
     *
     * Generated from protobuf field <code>.opamp.proto.RemoteConfigStatus remote_config_status = 7;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\RemoteConfigStatus $var
     * @return $this
     */
    public function setRemoteConfigStatus($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\RemoteConfigStatus::class);
        $this->remote_config_status = $var;

        return $this;
    }

    /**
     * The list of the Agent packages, including package statuses. This field SHOULD be
     * unset if this information is unchanged since the last AgentToServer message for
     * this Agent was sent in the stream.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.PackageStatuses package_statuses = 8;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\PackageStatuses|null
     */
    public function getPackageStatuses()
    {
        return $this->package_statuses;
    }

    public function hasPackageStatuses()
    {
        return isset($this->package_statuses);
    }

    public function clearPackageStatuses()
    {
        unset($this->package_statuses);
    }

    /**
     * The list of the Agent packages, including package statuses. This field SHOULD be
     * unset if this information is unchanged since the last AgentToServer message for
     * this Agent was sent in the stream.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.PackageStatuses package_statuses = 8;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\PackageStatuses $var
     * @return $this
     */
    public function setPackageStatuses($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\PackageStatuses::class);
        $this->package_statuses = $var;

        return $this;
    }

    /**
     * AgentDisconnect MUST be set in the last AgentToServer message sent from the
     * Agent to the Server.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentDisconnect agent_disconnect = 9;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\AgentDisconnect|null
     */
    public function getAgentDisconnect()
    {
        return $this->agent_disconnect;
    }

    public function hasAgentDisconnect()
    {
        return isset($this->agent_disconnect);
    }

    public function clearAgentDisconnect()
    {
        unset($this->agent_disconnect);
    }

    /**
     * AgentDisconnect MUST be set in the last AgentToServer message sent from the
     * Agent to the Server.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentDisconnect agent_disconnect = 9;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\AgentDisconnect $var
     * @return $this
     */
    public function setAgentDisconnect($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\AgentDisconnect::class);
        $this->agent_disconnect = $var;

        return $this;
    }

    /**
     * Bit flags as defined by AgentToServerFlags bit masks.
     *
     * Generated from protobuf field <code>uint64 flags = 10;</code>
     * @return int|string
     */
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Bit flags as defined by AgentToServerFlags bit masks.
     *
     * Generated from protobuf field <code>uint64 flags = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlags($var)
    {
        GPBUtil::checkUint64($var);
        $this->flags = $var;

        return $this;
    }

    /**
     * A request to create connection settings. This field is set for flows where
     * the Agent initiates the creation of connection settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsRequest connection_settings_request = 11;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsRequest|null
     */
    public function getConnectionSettingsRequest()
    {
        return $this->connection_settings_request;
    }

    public function hasConnectionSettingsRequest()
    {
        return isset($this->connection_settings_request);
    }

    public function clearConnectionSettingsRequest()
    {
        unset($this->connection_settings_request);
    }

    /**
     * A request to create connection settings. This field is set for flows where
     * the Agent initiates the creation of connection settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsRequest connection_settings_request = 11;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsRequest $var
     * @return $this
     */
    public function setConnectionSettingsRequest($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsRequest::class);
        $this->connection_settings_request = $var;

        return $this;
    }

    /**
     * A message indicating custom capabilities supported by the Agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomCapabilities custom_capabilities = 12;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\CustomCapabilities|null
     */
    public function getCustomCapabilities()
    {
        return $this->custom_capabilities;
    }

    public function hasCustomCapabilities()
    {
        return isset($this->custom_capabilities);
    }

    public function clearCustomCapabilities()
    {
        unset($this->custom_capabilities);
    }

    /**
     * A message indicating custom capabilities supported by the Agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomCapabilities custom_capabilities = 12;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\CustomCapabilities $var
     * @return $this
     */
    public function setCustomCapabilities($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\CustomCapabilities::class);
        $this->custom_capabilities = $var;

        return $this;
    }

    /**
     * A custom message sent from an Agent to the Server.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomMessage custom_message = 13;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\CustomMessage|null
     */
    public function getCustomMessage()
    {
        return $this->custom_message;
    }

    public function hasCustomMessage()
    {
        return isset($this->custom_message);
    }

    public function clearCustomMessage()
    {
        unset($this->custom_message);
    }

    /**
     * A custom message sent from an Agent to the Server.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomMessage custom_message = 13;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\CustomMessage $var
     * @return $this
     */
    public function setCustomMessage($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\CustomMessage::class);
        $this->custom_message = $var;

        return $this;
    }

    /**
     * A message indicating the components that are available for configuration on the agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.AvailableComponents available_components = 14;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\AvailableComponents|null
     */
    public function getAvailableComponents()
    {
        return $this->available_components;
    }

    public function hasAvailableComponents()
    {
        return isset($this->available_components);
    }

    public function clearAvailableComponents()
    {
        unset($this->available_components);
    }

    /**
     * A message indicating the components that are available for configuration on the agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.AvailableComponents available_components = 14;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\AvailableComponents $var
     * @return $this
     */
    public function setAvailableComponents($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\AvailableComponents::class);
        $this->available_components = $var;

        return $this;
    }

    /**
     * The status of the OfferedConnectionSettings that was previously received
     * from the Server. This field SHOULD be unset if the offered connection
     * settings status is unchanged since the last AgentToServer message.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsStatus connection_settings_status = 15;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsStatus|null
     */
    public function getConnectionSettingsStatus()
    {
        return $this->connection_settings_status;
    }

    public function hasConnectionSettingsStatus()
    {
        return isset($this->connection_settings_status);
    }

    public function clearConnectionSettingsStatus()
    {
        unset($this->connection_settings_status);
    }

    /**
     * The status of the OfferedConnectionSettings that was previously received
     * from the Server. This field SHOULD be unset if the offered connection
     * settings status is unchanged since the last AgentToServer message.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsStatus connection_settings_status = 15;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsStatus $var
     * @return $this
     */
    public function setConnectionSettingsStatus($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsStatus::class);
        $this->connection_settings_status = $var;

        return $this;
    }

}

