<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.AgentConfigMap</code>
 */
class AgentConfigMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Map of configs. Keys are config file names or config section names.
     * The configuration is assumed to be a collection of one or more named config files
     * or sections.
     * For agents that use a single config file or section the map SHOULD contain a single
     * entry and the key may be an empty string.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.AgentConfigFile> config_map = 1;</code>
     */
    private $config_map;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $config_map
     *           Map of configs. Keys are config file names or config section names.
     *           The configuration is assumed to be a collection of one or more named config files
     *           or sections.
     *           For agents that use a single config file or section the map SHOULD contain a single
     *           entry and the key may be an empty string.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Map of configs. Keys are config file names or config section names.
     * The configuration is assumed to be a collection of one or more named config files
     * or sections.
     * For agents that use a single config file or section the map SHOULD contain a single
     * entry and the key may be an empty string.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.AgentConfigFile> config_map = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getConfigMap()
    {
        return $this->config_map;
    }

    /**
     * Map of configs. Keys are config file names or config section names.
     * The configuration is assumed to be a collection of one or more named config files
     * or sections.
     * For agents that use a single config file or section the map SHOULD contain a single
     * entry and the key may be an empty string.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.AgentConfigFile> config_map = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setConfigMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \GeneratedForElasticOTelTests\OpampProto\AgentConfigFile::class);
        $this->config_map = $arr;

        return $this;
    }

}

