<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Properties related to identification of the Agent, which can be overridden
 * by the Server if needed
 *
 * Generated from protobuf message <code>opamp.proto.AgentIdentification</code>
 */
class AgentIdentification extends \Google\Protobuf\Internal\Message
{
    /**
     * When new_instance_uid is set, Agent MUST update instance_uid
     * to the value provided and use it for all further communication.
     * MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *
     * Generated from protobuf field <code>bytes new_instance_uid = 1;</code>
     */
    protected $new_instance_uid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $new_instance_uid
     *           When new_instance_uid is set, Agent MUST update instance_uid
     *           to the value provided and use it for all further communication.
     *           MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * When new_instance_uid is set, Agent MUST update instance_uid
     * to the value provided and use it for all further communication.
     * MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *
     * Generated from protobuf field <code>bytes new_instance_uid = 1;</code>
     * @return string
     */
    public function getNewInstanceUid()
    {
        return $this->new_instance_uid;
    }

    /**
     * When new_instance_uid is set, Agent MUST update instance_uid
     * to the value provided and use it for all further communication.
     * MUST be 16 bytes long and SHOULD be generated using the UUID v7 spec.
     *
     * Generated from protobuf field <code>bytes new_instance_uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNewInstanceUid($var)
    {
        GPBUtil::checkString($var, False);
        $this->new_instance_uid = $var;

        return $this;
    }

}

