<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.AgentRemoteConfig</code>
 */
class AgentRemoteConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Agent config offered by the management Server to the Agent instance. SHOULD NOT be
     * set if the config for this Agent has not changed since it was last requested (i.e.
     * AgentConfigRequest.last_remote_config_hash field is equal to
     * AgentConfigResponse.config_hash field).
     *
     * Generated from protobuf field <code>.opamp.proto.AgentConfigMap config = 1;</code>
     */
    protected $config = null;
    /**
     * Hash of "config". The Agent SHOULD include this value in subsequent
     * RemoteConfigStatus messages in the last_remote_config_hash field. This in turn
     * allows the management Server to identify that a new config is available for the Agent.
     * This field MUST be always set if the management Server supports remote configuration
     * of agents.
     * Management Server must choose a hashing function that guarantees lack of hash
     * collisions in practice.
     *
     * Generated from protobuf field <code>bytes config_hash = 2;</code>
     */
    protected $config_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ElasticOTelTests\Generated\OpampProto\AgentConfigMap $config
     *           Agent config offered by the management Server to the Agent instance. SHOULD NOT be
     *           set if the config for this Agent has not changed since it was last requested (i.e.
     *           AgentConfigRequest.last_remote_config_hash field is equal to
     *           AgentConfigResponse.config_hash field).
     *     @type string $config_hash
     *           Hash of "config". The Agent SHOULD include this value in subsequent
     *           RemoteConfigStatus messages in the last_remote_config_hash field. This in turn
     *           allows the management Server to identify that a new config is available for the Agent.
     *           This field MUST be always set if the management Server supports remote configuration
     *           of agents.
     *           Management Server must choose a hashing function that guarantees lack of hash
     *           collisions in practice.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Agent config offered by the management Server to the Agent instance. SHOULD NOT be
     * set if the config for this Agent has not changed since it was last requested (i.e.
     * AgentConfigRequest.last_remote_config_hash field is equal to
     * AgentConfigResponse.config_hash field).
     *
     * Generated from protobuf field <code>.opamp.proto.AgentConfigMap config = 1;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\AgentConfigMap|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * Agent config offered by the management Server to the Agent instance. SHOULD NOT be
     * set if the config for this Agent has not changed since it was last requested (i.e.
     * AgentConfigRequest.last_remote_config_hash field is equal to
     * AgentConfigResponse.config_hash field).
     *
     * Generated from protobuf field <code>.opamp.proto.AgentConfigMap config = 1;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\AgentConfigMap $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\AgentConfigMap::class);
        $this->config = $var;

        return $this;
    }

    /**
     * Hash of "config". The Agent SHOULD include this value in subsequent
     * RemoteConfigStatus messages in the last_remote_config_hash field. This in turn
     * allows the management Server to identify that a new config is available for the Agent.
     * This field MUST be always set if the management Server supports remote configuration
     * of agents.
     * Management Server must choose a hashing function that guarantees lack of hash
     * collisions in practice.
     *
     * Generated from protobuf field <code>bytes config_hash = 2;</code>
     * @return string
     */
    public function getConfigHash()
    {
        return $this->config_hash;
    }

    /**
     * Hash of "config". The Agent SHOULD include this value in subsequent
     * RemoteConfigStatus messages in the last_remote_config_hash field. This in turn
     * allows the management Server to identify that a new config is available for the Agent.
     * This field MUST be always set if the management Server supports remote configuration
     * of agents.
     * Management Server must choose a hashing function that guarantees lack of hash
     * collisions in practice.
     *
     * Generated from protobuf field <code>bytes config_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConfigHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->config_hash = $var;

        return $this;
    }

}

