<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anyvalue.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
 * since oneof in AnyValue does not allow repeated fields.
 *
 * Generated from protobuf message <code>opamp.proto.ArrayValue</code>
 */
class ArrayValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Array of values. The array may be empty (contain 0 elements).
     *
     * Generated from protobuf field <code>repeated .opamp.proto.AnyValue values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\ElasticOTelTests\Generated\OpampProto\AnyValue>|\Google\Protobuf\Internal\RepeatedField $values
     *           Array of values. The array may be empty (contain 0 elements).
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Anyvalue::initOnce();
        parent::__construct($data);
    }

    /**
     * Array of values. The array may be empty (contain 0 elements).
     *
     * Generated from protobuf field <code>repeated .opamp.proto.AnyValue values = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Array of values. The array may be empty (contain 0 elements).
     *
     * Generated from protobuf field <code>repeated .opamp.proto.AnyValue values = 1;</code>
     * @param array<\ElasticOTelTests\Generated\OpampProto\AnyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ElasticOTelTests\Generated\OpampProto\AnyValue::class);
        $this->values = $arr;

        return $this;
    }

}

