<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.CertificateRequest</code>
 */
class CertificateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * PEM-encoded Client Certificate Signing Request (CSR), signed by client's private key.
     * The Server SHOULD validate the request and SHOULD respond with a
     * OpAMPConnectionSettings where the certificate.cert contains the issued
     * certificate.
     *
     * Generated from protobuf field <code>bytes csr = 1;</code>
     */
    protected $csr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $csr
     *           PEM-encoded Client Certificate Signing Request (CSR), signed by client's private key.
     *           The Server SHOULD validate the request and SHOULD respond with a
     *           OpAMPConnectionSettings where the certificate.cert contains the issued
     *           certificate.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * PEM-encoded Client Certificate Signing Request (CSR), signed by client's private key.
     * The Server SHOULD validate the request and SHOULD respond with a
     * OpAMPConnectionSettings where the certificate.cert contains the issued
     * certificate.
     *
     * Generated from protobuf field <code>bytes csr = 1;</code>
     * @return string
     */
    public function getCsr()
    {
        return $this->csr;
    }

    /**
     * PEM-encoded Client Certificate Signing Request (CSR), signed by client's private key.
     * The Server SHOULD validate the request and SHOULD respond with a
     * OpAMPConnectionSettings where the certificate.cert contains the issued
     * certificate.
     *
     * Generated from protobuf field <code>bytes csr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCsr($var)
    {
        GPBUtil::checkString($var, False);
        $this->csr = $var;

        return $this;
    }

}

