<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use UnexpectedValueException;

/**
 * Status: [Beta]
 *
 * Protobuf type <code>opamp.proto.CommandType</code>
 */
class CommandType
{
    /**
     * The Agent should restart. This request will be ignored if the Agent does not
     * support restart.
     *
     * Generated from protobuf enum <code>CommandType_Restart = 0;</code>
     */
    const CommandType_Restart = 0;

    private static $valueToName = [
        self::CommandType_Restart => 'CommandType_Restart',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

