<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.ComponentDetails</code>
 */
class ComponentDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Extra key/value pairs that may be used to describe the component.
     * The key/value pairs are according to semantic conventions, see:
     * https://opentelemetry.io/docs/specs/semconv/
     * For example, you may use the "code" semantic conventions to
     * report the location of the code for a specific component:
     * https://opentelemetry.io/docs/specs/semconv/attributes-registry/code/
     * Or you may use the "vcs" semantic conventions to report the
     * repository the component may be a part of:
     * https://opentelemetry.io/docs/specs/semconv/attributes-registry/vcs/
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue metadata = 1;</code>
     */
    private $metadata;
    /**
     * A map of component ID to sub components details. It can nest as deeply as needed to
     * describe the underlying system.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentDetails> sub_component_map = 2;</code>
     */
    private $sub_component_map;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\GeneratedForElasticOTelTests\OpampProto\KeyValue>|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Extra key/value pairs that may be used to describe the component.
     *           The key/value pairs are according to semantic conventions, see:
     *           https://opentelemetry.io/docs/specs/semconv/
     *           For example, you may use the "code" semantic conventions to
     *           report the location of the code for a specific component:
     *           https://opentelemetry.io/docs/specs/semconv/attributes-registry/code/
     *           Or you may use the "vcs" semantic conventions to report the
     *           repository the component may be a part of:
     *           https://opentelemetry.io/docs/specs/semconv/attributes-registry/vcs/
     *     @type array|\Google\Protobuf\Internal\MapField $sub_component_map
     *           A map of component ID to sub components details. It can nest as deeply as needed to
     *           describe the underlying system.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Extra key/value pairs that may be used to describe the component.
     * The key/value pairs are according to semantic conventions, see:
     * https://opentelemetry.io/docs/specs/semconv/
     * For example, you may use the "code" semantic conventions to
     * report the location of the code for a specific component:
     * https://opentelemetry.io/docs/specs/semconv/attributes-registry/code/
     * Or you may use the "vcs" semantic conventions to report the
     * repository the component may be a part of:
     * https://opentelemetry.io/docs/specs/semconv/attributes-registry/vcs/
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue metadata = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Extra key/value pairs that may be used to describe the component.
     * The key/value pairs are according to semantic conventions, see:
     * https://opentelemetry.io/docs/specs/semconv/
     * For example, you may use the "code" semantic conventions to
     * report the location of the code for a specific component:
     * https://opentelemetry.io/docs/specs/semconv/attributes-registry/code/
     * Or you may use the "vcs" semantic conventions to report the
     * repository the component may be a part of:
     * https://opentelemetry.io/docs/specs/semconv/attributes-registry/vcs/
     *
     * Generated from protobuf field <code>repeated .opamp.proto.KeyValue metadata = 1;</code>
     * @param array<\GeneratedForElasticOTelTests\OpampProto\KeyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GeneratedForElasticOTelTests\OpampProto\KeyValue::class);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * A map of component ID to sub components details. It can nest as deeply as needed to
     * describe the underlying system.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentDetails> sub_component_map = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSubComponentMap()
    {
        return $this->sub_component_map;
    }

    /**
     * A map of component ID to sub components details. It can nest as deeply as needed to
     * describe the underlying system.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentDetails> sub_component_map = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSubComponentMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \GeneratedForElasticOTelTests\OpampProto\ComponentDetails::class);
        $this->sub_component_map = $arr;

        return $this;
    }

}

