<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The health of the Agent and sub-components
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.ComponentHealth</code>
 */
class ComponentHealth extends \Google\Protobuf\Internal\Message
{
    /**
     * Set to true if the component is up and healthy.
     *
     * Generated from protobuf field <code>bool healthy = 1;</code>
     */
    protected $healthy = false;
    /**
     * Timestamp since the component is up, i.e. when the component was started.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * If the component is not running MUST be set to 0.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     */
    protected $start_time_unix_nano = 0;
    /**
     * Human-readable error message if the component is in erroneous state. SHOULD be set
     * when healthy==false.
     *
     * Generated from protobuf field <code>string last_error = 3;</code>
     */
    protected $last_error = '';
    /**
     * Component status represented as a string. The status values are defined by agent-specific
     * semantics and not at the protocol level.
     *
     * Generated from protobuf field <code>string status = 4;</code>
     */
    protected $status = '';
    /**
     * The time when the component status was observed. Value is UNIX Epoch time in
     * nanoseconds since 00:00:00 UTC on 1 January 1970.
     *
     * Generated from protobuf field <code>fixed64 status_time_unix_nano = 5;</code>
     */
    protected $status_time_unix_nano = 0;
    /**
     * A map to store more granular, sub-component health. It can nest as deeply as needed to
     * describe the underlying system.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentHealth> component_health_map = 6;</code>
     */
    private $component_health_map;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $healthy
     *           Set to true if the component is up and healthy.
     *     @type int|string $start_time_unix_nano
     *           Timestamp since the component is up, i.e. when the component was started.
     *           Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     *           If the component is not running MUST be set to 0.
     *     @type string $last_error
     *           Human-readable error message if the component is in erroneous state. SHOULD be set
     *           when healthy==false.
     *     @type string $status
     *           Component status represented as a string. The status values are defined by agent-specific
     *           semantics and not at the protocol level.
     *     @type int|string $status_time_unix_nano
     *           The time when the component status was observed. Value is UNIX Epoch time in
     *           nanoseconds since 00:00:00 UTC on 1 January 1970.
     *     @type array|\Google\Protobuf\Internal\MapField $component_health_map
     *           A map to store more granular, sub-component health. It can nest as deeply as needed to
     *           describe the underlying system.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Set to true if the component is up and healthy.
     *
     * Generated from protobuf field <code>bool healthy = 1;</code>
     * @return bool
     */
    public function getHealthy()
    {
        return $this->healthy;
    }

    /**
     * Set to true if the component is up and healthy.
     *
     * Generated from protobuf field <code>bool healthy = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setHealthy($var)
    {
        GPBUtil::checkBool($var);
        $this->healthy = $var;

        return $this;
    }

    /**
     * Timestamp since the component is up, i.e. when the component was started.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * If the component is not running MUST be set to 0.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     * @return int|string
     */
    public function getStartTimeUnixNano()
    {
        return $this->start_time_unix_nano;
    }

    /**
     * Timestamp since the component is up, i.e. when the component was started.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * If the component is not running MUST be set to 0.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimeUnixNano($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_time_unix_nano = $var;

        return $this;
    }

    /**
     * Human-readable error message if the component is in erroneous state. SHOULD be set
     * when healthy==false.
     *
     * Generated from protobuf field <code>string last_error = 3;</code>
     * @return string
     */
    public function getLastError()
    {
        return $this->last_error;
    }

    /**
     * Human-readable error message if the component is in erroneous state. SHOULD be set
     * when healthy==false.
     *
     * Generated from protobuf field <code>string last_error = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastError($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_error = $var;

        return $this;
    }

    /**
     * Component status represented as a string. The status values are defined by agent-specific
     * semantics and not at the protocol level.
     *
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Component status represented as a string. The status values are defined by agent-specific
     * semantics and not at the protocol level.
     *
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * The time when the component status was observed. Value is UNIX Epoch time in
     * nanoseconds since 00:00:00 UTC on 1 January 1970.
     *
     * Generated from protobuf field <code>fixed64 status_time_unix_nano = 5;</code>
     * @return int|string
     */
    public function getStatusTimeUnixNano()
    {
        return $this->status_time_unix_nano;
    }

    /**
     * The time when the component status was observed. Value is UNIX Epoch time in
     * nanoseconds since 00:00:00 UTC on 1 January 1970.
     *
     * Generated from protobuf field <code>fixed64 status_time_unix_nano = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatusTimeUnixNano($var)
    {
        GPBUtil::checkUint64($var);
        $this->status_time_unix_nano = $var;

        return $this;
    }

    /**
     * A map to store more granular, sub-component health. It can nest as deeply as needed to
     * describe the underlying system.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentHealth> component_health_map = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getComponentHealthMap()
    {
        return $this->component_health_map;
    }

    /**
     * A map to store more granular, sub-component health. It can nest as deeply as needed to
     * describe the underlying system.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentHealth> component_health_map = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setComponentHealthMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \ElasticOTelTests\Generated\OpampProto\ComponentHealth::class);
        $this->component_health_map = $arr;

        return $this;
    }

}

