<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use UnexpectedValueException;

/**
 * Status: [Development]
 *
 * Protobuf type <code>opamp.proto.ConnectionSettingsStatuses</code>
 */
class ConnectionSettingsStatuses
{
    /**
     * The value of status field is not set.
     *
     * Generated from protobuf enum <code>ConnectionSettingsStatuses_UNSET = 0;</code>
     */
    const ConnectionSettingsStatuses_UNSET = 0;
    /**
     * ConnectionSettings were successfully applied by the Agent.
     *
     * Generated from protobuf enum <code>ConnectionSettingsStatuses_APPLIED = 1;</code>
     */
    const ConnectionSettingsStatuses_APPLIED = 1;
    /**
     * Agent is currently applying the ConnectionSettings that it received.
     *
     * Generated from protobuf enum <code>ConnectionSettingsStatuses_APPLYING = 2;</code>
     */
    const ConnectionSettingsStatuses_APPLYING = 2;
    /**
     * Agent tried to apply the ConnectionSettings it received earlier, but failed.
     * See error_message for more details.
     *
     * Generated from protobuf enum <code>ConnectionSettingsStatuses_FAILED = 3;</code>
     */
    const ConnectionSettingsStatuses_FAILED = 3;

    private static $valueToName = [
        self::ConnectionSettingsStatuses_UNSET => 'ConnectionSettingsStatuses_UNSET',
        self::ConnectionSettingsStatuses_APPLIED => 'ConnectionSettingsStatuses_APPLIED',
        self::ConnectionSettingsStatuses_APPLYING => 'ConnectionSettingsStatuses_APPLYING',
        self::ConnectionSettingsStatuses_FAILED => 'ConnectionSettingsStatuses_FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

