<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.ConnectionSettingsStatus</code>
 */
class ConnectionSettingsStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * The hash of the connection settings that was last recieved by this Agent
     * in the connection_settings.hash field. The Server SHOULD compare this
     * hash with the OfferedConnectionSettings hash it has for the Agent and if
     * the hashes are different the Server MUST include the connection_settings
     * field in the response in the ServerToAgent message.
     *
     * Generated from protobuf field <code>bytes last_connection_settings_hash = 1;</code>
     */
    protected $last_connection_settings_hash = '';
    /**
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsStatuses status = 2;</code>
     */
    protected $status = 0;
    /**
     * Optional error message if status==FAILED.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $last_connection_settings_hash
     *           The hash of the connection settings that was last recieved by this Agent
     *           in the connection_settings.hash field. The Server SHOULD compare this
     *           hash with the OfferedConnectionSettings hash it has for the Agent and if
     *           the hashes are different the Server MUST include the connection_settings
     *           field in the response in the ServerToAgent message.
     *     @type int $status
     *     @type string $error_message
     *           Optional error message if status==FAILED.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * The hash of the connection settings that was last recieved by this Agent
     * in the connection_settings.hash field. The Server SHOULD compare this
     * hash with the OfferedConnectionSettings hash it has for the Agent and if
     * the hashes are different the Server MUST include the connection_settings
     * field in the response in the ServerToAgent message.
     *
     * Generated from protobuf field <code>bytes last_connection_settings_hash = 1;</code>
     * @return string
     */
    public function getLastConnectionSettingsHash()
    {
        return $this->last_connection_settings_hash;
    }

    /**
     * The hash of the connection settings that was last recieved by this Agent
     * in the connection_settings.hash field. The Server SHOULD compare this
     * hash with the OfferedConnectionSettings hash it has for the Agent and if
     * the hashes are different the Server MUST include the connection_settings
     * field in the response in the ServerToAgent message.
     *
     * Generated from protobuf field <code>bytes last_connection_settings_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLastConnectionSettingsHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->last_connection_settings_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsStatuses status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsStatuses status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \ElasticOTelTests\Generated\OpampProto\ConnectionSettingsStatuses::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Optional error message if status==FAILED.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Optional error message if status==FAILED.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

