<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ConnectionSettingsRequest is a request from the Agent to the Server to create
 * and respond with an offer of connection settings for the Agent.
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.ConnectionSettingsRequest</code>
 */
class ConnectionSettingsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Request for OpAMP connection settings. If this field is unset
     * then the ConnectionSettingsRequest message is empty and is not actionable
     * for the Server.
     *
     * Generated from protobuf field <code>.opamp.proto.OpAMPConnectionSettingsRequest opamp = 1;</code>
     */
    protected $opamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GeneratedForElasticOTelTests\OpampProto\OpAMPConnectionSettingsRequest $opamp
     *           Request for OpAMP connection settings. If this field is unset
     *           then the ConnectionSettingsRequest message is empty and is not actionable
     *           for the Server.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Request for OpAMP connection settings. If this field is unset
     * then the ConnectionSettingsRequest message is empty and is not actionable
     * for the Server.
     *
     * Generated from protobuf field <code>.opamp.proto.OpAMPConnectionSettingsRequest opamp = 1;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\OpAMPConnectionSettingsRequest|null
     */
    public function getOpamp()
    {
        return $this->opamp;
    }

    public function hasOpamp()
    {
        return isset($this->opamp);
    }

    public function clearOpamp()
    {
        unset($this->opamp);
    }

    /**
     * Request for OpAMP connection settings. If this field is unset
     * then the ConnectionSettingsRequest message is empty and is not actionable
     * for the Server.
     *
     * Generated from protobuf field <code>.opamp.proto.OpAMPConnectionSettingsRequest opamp = 1;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\OpAMPConnectionSettingsRequest $var
     * @return $this
     */
    public function setOpamp($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\OpAMPConnectionSettingsRequest::class);
        $this->opamp = $var;

        return $this;
    }

}

