<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.CustomCapabilities</code>
 */
class CustomCapabilities extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of custom capabilities that are supported. Each capability is a reverse FQDN
     * with optional version information that uniquely identifies the custom capability
     * and should match a capability specified in a supported CustomMessage.
     * Status: [Development]
     *
     * Generated from protobuf field <code>repeated string capabilities = 1;</code>
     */
    private $capabilities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $capabilities
     *           A list of custom capabilities that are supported. Each capability is a reverse FQDN
     *           with optional version information that uniquely identifies the custom capability
     *           and should match a capability specified in a supported CustomMessage.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of custom capabilities that are supported. Each capability is a reverse FQDN
     * with optional version information that uniquely identifies the custom capability
     * and should match a capability specified in a supported CustomMessage.
     * Status: [Development]
     *
     * Generated from protobuf field <code>repeated string capabilities = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * A list of custom capabilities that are supported. Each capability is a reverse FQDN
     * with optional version information that uniquely identifies the custom capability
     * and should match a capability specified in a supported CustomMessage.
     * Status: [Development]
     *
     * Generated from protobuf field <code>repeated string capabilities = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCapabilities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->capabilities = $arr;

        return $this;
    }

}

