<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.DownloadableFile</code>
 */
class DownloadableFile extends \Google\Protobuf\Internal\Message
{
    /**
     * The URL from which the file can be downloaded using HTTP GET request.
     * The Server at the specified URL SHOULD support range requests
     * to allow for resuming downloads.
     *
     * Generated from protobuf field <code>string download_url = 1;</code>
     */
    protected $download_url = '';
    /**
     * The hash of the file content. Can be used by the Agent to verify that the file
     * was downloaded correctly.
     *
     * Generated from protobuf field <code>bytes content_hash = 2;</code>
     */
    protected $content_hash = '';
    /**
     * Optional signature of the file content. Can be used by the Agent to verify the
     * authenticity of the downloaded file, for example can be the
     * [detached GPG signature](https://www.gnupg.org/gph/en/manual/x135.html#AEN160).
     * The exact signing and verification method is Agent specific. See
     * https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#code-signing
     * for recommendations.
     *
     * Generated from protobuf field <code>bytes signature = 3;</code>
     */
    protected $signature = '';
    /**
     * Optional headers to use when downloading a file. Typically used to set
     * access tokens or other authorization headers. For HTTP-based protocols
     * the Agent should set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 4;</code>
     */
    protected $headers = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $download_url
     *           The URL from which the file can be downloaded using HTTP GET request.
     *           The Server at the specified URL SHOULD support range requests
     *           to allow for resuming downloads.
     *     @type string $content_hash
     *           The hash of the file content. Can be used by the Agent to verify that the file
     *           was downloaded correctly.
     *     @type string $signature
     *           Optional signature of the file content. Can be used by the Agent to verify the
     *           authenticity of the downloaded file, for example can be the
     *           [detached GPG signature](https://www.gnupg.org/gph/en/manual/x135.html#AEN160).
     *           The exact signing and verification method is Agent specific. See
     *           https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#code-signing
     *           for recommendations.
     *     @type \ElasticOTelTests\Generated\OpampProto\Headers $headers
     *           Optional headers to use when downloading a file. Typically used to set
     *           access tokens or other authorization headers. For HTTP-based protocols
     *           the Agent should set these in the request headers.
     *           For example:
     *           key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * The URL from which the file can be downloaded using HTTP GET request.
     * The Server at the specified URL SHOULD support range requests
     * to allow for resuming downloads.
     *
     * Generated from protobuf field <code>string download_url = 1;</code>
     * @return string
     */
    public function getDownloadUrl()
    {
        return $this->download_url;
    }

    /**
     * The URL from which the file can be downloaded using HTTP GET request.
     * The Server at the specified URL SHOULD support range requests
     * to allow for resuming downloads.
     *
     * Generated from protobuf field <code>string download_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_url = $var;

        return $this;
    }

    /**
     * The hash of the file content. Can be used by the Agent to verify that the file
     * was downloaded correctly.
     *
     * Generated from protobuf field <code>bytes content_hash = 2;</code>
     * @return string
     */
    public function getContentHash()
    {
        return $this->content_hash;
    }

    /**
     * The hash of the file content. Can be used by the Agent to verify that the file
     * was downloaded correctly.
     *
     * Generated from protobuf field <code>bytes content_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->content_hash = $var;

        return $this;
    }

    /**
     * Optional signature of the file content. Can be used by the Agent to verify the
     * authenticity of the downloaded file, for example can be the
     * [detached GPG signature](https://www.gnupg.org/gph/en/manual/x135.html#AEN160).
     * The exact signing and verification method is Agent specific. See
     * https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#code-signing
     * for recommendations.
     *
     * Generated from protobuf field <code>bytes signature = 3;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Optional signature of the file content. Can be used by the Agent to verify the
     * authenticity of the downloaded file, for example can be the
     * [detached GPG signature](https://www.gnupg.org/gph/en/manual/x135.html#AEN160).
     * The exact signing and verification method is Agent specific. See
     * https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#code-signing
     * for recommendations.
     *
     * Generated from protobuf field <code>bytes signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Optional headers to use when downloading a file. Typically used to set
     * access tokens or other authorization headers. For HTTP-based protocols
     * the Agent should set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 4;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\Headers|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Optional headers to use when downloading a file. Typically used to set
     * access tokens or other authorization headers. For HTTP-based protocols
     * the Agent should set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 4;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\Headers::class);
        $this->headers = $var;

        return $this;
    }

}

