<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.EffectiveConfig</code>
 */
class EffectiveConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * The effective config of the Agent.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentConfigMap config_map = 1;</code>
     */
    protected $config_map = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ElasticOTelTests\Generated\OpampProto\AgentConfigMap $config_map
     *           The effective config of the Agent.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * The effective config of the Agent.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentConfigMap config_map = 1;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\AgentConfigMap|null
     */
    public function getConfigMap()
    {
        return $this->config_map;
    }

    public function hasConfigMap()
    {
        return isset($this->config_map);
    }

    public function clearConfigMap()
    {
        unset($this->config_map);
    }

    /**
     * The effective config of the Agent.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentConfigMap config_map = 1;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\AgentConfigMap $var
     * @return $this
     */
    public function setConfigMap($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\AgentConfigMap::class);
        $this->config_map = $var;

        return $this;
    }

}

