<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.Headers</code>
 */
class Headers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .opamp.proto.Header headers = 1;</code>
     */
    private $headers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\ElasticOTelTests\Generated\OpampProto\Header>|\Google\Protobuf\Internal\RepeatedField $headers
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .opamp.proto.Header headers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>repeated .opamp.proto.Header headers = 1;</code>
     * @param array<\ElasticOTelTests\Generated\OpampProto\Header>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ElasticOTelTests\Generated\OpampProto\Header::class);
        $this->headers = $arr;

        return $this;
    }

}

