<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * OpAMPConnectionSettingsRequest is a request for the Server to produce
 * a OpAMPConnectionSettings in its response.
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.OpAMPConnectionSettingsRequest</code>
 */
class OpAMPConnectionSettingsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A request to create a client certificate. This is used to initiate a
     * Client Signing Request (CSR) flow.
     * Required.
     *
     * Generated from protobuf field <code>.opamp.proto.CertificateRequest certificate_request = 1;</code>
     */
    protected $certificate_request = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GeneratedForElasticOTelTests\OpampProto\CertificateRequest $certificate_request
     *           A request to create a client certificate. This is used to initiate a
     *           Client Signing Request (CSR) flow.
     *           Required.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A request to create a client certificate. This is used to initiate a
     * Client Signing Request (CSR) flow.
     * Required.
     *
     * Generated from protobuf field <code>.opamp.proto.CertificateRequest certificate_request = 1;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\CertificateRequest|null
     */
    public function getCertificateRequest()
    {
        return $this->certificate_request;
    }

    public function hasCertificateRequest()
    {
        return isset($this->certificate_request);
    }

    public function clearCertificateRequest()
    {
        unset($this->certificate_request);
    }

    /**
     * A request to create a client certificate. This is used to initiate a
     * Client Signing Request (CSR) flow.
     * Required.
     *
     * Generated from protobuf field <code>.opamp.proto.CertificateRequest certificate_request = 1;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\CertificateRequest $var
     * @return $this
     */
    public function setCertificateRequest($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\CertificateRequest::class);
        $this->certificate_request = $var;

        return $this;
    }

}

