<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The OtherConnectionSettings message is a collection of fields which comprise an
 * offer from the Server to the Agent to use the specified settings for a network
 * connection. It is not required that all fields in this message are specified.
 * The Server may specify only some of the fields, in which case it means that
 * the Server offers the Agent to change only those fields, while keeping the
 * rest of the fields unchanged.
 * For example the Server may send a ConnectionSettings message with only the
 * certificate field set, while all other fields are unset. This means that
 * the Server wants the Agent to use a new certificate and continue sending to
 * the destination it is currently sending using the current header and other
 * settings.
 * For fields which reference other messages the field is considered unset
 * when the reference is unset.
 * For primitive field (string) we rely on the "flags" to describe that the
 * field is not set (this is done to overcome the limitation of old protoc
 * compilers don't generate methods that allow to check for the presence of
 * the field.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.OtherConnectionSettings</code>
 */
class OtherConnectionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * A URL, host:port or some other destination specifier.
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     */
    protected $destination_endpoint = '';
    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     */
    protected $headers = null;
    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     */
    protected $certificate = null;
    /**
     * Other connection settings. These are Agent-specific and are up to the Agent
     * interpret.
     *
     * Generated from protobuf field <code>map<string, string> other_settings = 4;</code>
     */
    private $other_settings;
    /**
     * Optional connection specific TLS settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.TLSConnectionSettings tls = 5;</code>
     */
    protected $tls = null;
    /**
     * Optional connection specific proxy settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ProxyConnectionSettings proxy = 6;</code>
     */
    protected $proxy = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $destination_endpoint
     *           A URL, host:port or some other destination specifier.
     *     @type \ElasticOTelTests\Generated\OpampProto\Headers $headers
     *           Optional headers to use when connecting. Typically used to set access tokens or
     *           other authorization headers. For HTTP-based protocols the Agent should
     *           set these in the request headers.
     *           For example:
     *           key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *     @type \ElasticOTelTests\Generated\OpampProto\TLSCertificate $certificate
     *           The Agent should use the offered certificate to connect to the destination
     *           from now on. If the Agent is able to validate and connect using the offered
     *           certificate the Agent SHOULD forget any previous client certificates
     *           for this connection.
     *           This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     *           This field can be used to perform a client certificate revocation/rotation.
     *     @type array|\Google\Protobuf\Internal\MapField $other_settings
     *           Other connection settings. These are Agent-specific and are up to the Agent
     *           interpret.
     *     @type \ElasticOTelTests\Generated\OpampProto\TLSConnectionSettings $tls
     *           Optional connection specific TLS settings.
     *           Status: [Development]
     *     @type \ElasticOTelTests\Generated\OpampProto\ProxyConnectionSettings $proxy
     *           Optional connection specific proxy settings.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A URL, host:port or some other destination specifier.
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     * @return string
     */
    public function getDestinationEndpoint()
    {
        return $this->destination_endpoint;
    }

    /**
     * A URL, host:port or some other destination specifier.
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDestinationEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination_endpoint = $var;

        return $this;
    }

    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\Headers|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\Headers::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\TLSCertificate|null
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    public function hasCertificate()
    {
        return isset($this->certificate);
    }

    public function clearCertificate()
    {
        unset($this->certificate);
    }

    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\TLSCertificate $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\TLSCertificate::class);
        $this->certificate = $var;

        return $this;
    }

    /**
     * Other connection settings. These are Agent-specific and are up to the Agent
     * interpret.
     *
     * Generated from protobuf field <code>map<string, string> other_settings = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOtherSettings()
    {
        return $this->other_settings;
    }

    /**
     * Other connection settings. These are Agent-specific and are up to the Agent
     * interpret.
     *
     * Generated from protobuf field <code>map<string, string> other_settings = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOtherSettings($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->other_settings = $arr;

        return $this;
    }

    /**
     * Optional connection specific TLS settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.TLSConnectionSettings tls = 5;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\TLSConnectionSettings|null
     */
    public function getTls()
    {
        return $this->tls;
    }

    public function hasTls()
    {
        return isset($this->tls);
    }

    public function clearTls()
    {
        unset($this->tls);
    }

    /**
     * Optional connection specific TLS settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.TLSConnectionSettings tls = 5;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\TLSConnectionSettings $var
     * @return $this
     */
    public function setTls($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\TLSConnectionSettings::class);
        $this->tls = $var;

        return $this;
    }

    /**
     * Optional connection specific proxy settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ProxyConnectionSettings proxy = 6;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\ProxyConnectionSettings|null
     */
    public function getProxy()
    {
        return $this->proxy;
    }

    public function hasProxy()
    {
        return isset($this->proxy);
    }

    public function clearProxy()
    {
        unset($this->proxy);
    }

    /**
     * Optional connection specific proxy settings.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.ProxyConnectionSettings proxy = 6;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\ProxyConnectionSettings $var
     * @return $this
     */
    public function setProxy($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\ProxyConnectionSettings::class);
        $this->proxy = $var;

        return $this;
    }

}

