<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use UnexpectedValueException;

/**
 * The status of this package.
 * Status: [Beta]
 *
 * Protobuf type <code>opamp.proto.PackageStatusEnum</code>
 */
class PackageStatusEnum
{
    /**
     * Package is successfully installed by the Agent.
     * The error_message field MUST NOT be set.
     *
     * Generated from protobuf enum <code>PackageStatusEnum_Installed = 0;</code>
     */
    const PackageStatusEnum_Installed = 0;
    /**
     * Installation of this package has not yet started.
     *
     * Generated from protobuf enum <code>PackageStatusEnum_InstallPending = 1;</code>
     */
    const PackageStatusEnum_InstallPending = 1;
    /**
     * Agent is currently installing the package.
     * server_offered_hash field MUST be set to indicate the version that the
     * Agent is installing. The error_message field MUST NOT be set.
     *
     * Generated from protobuf enum <code>PackageStatusEnum_Installing = 2;</code>
     */
    const PackageStatusEnum_Installing = 2;
    /**
     * Agent tried to install the package but installation failed.
     * server_offered_hash field MUST be set to indicate the version that the Agent
     * tried to install. The error_message may also contain more details about
     * the failure.
     *
     * Generated from protobuf enum <code>PackageStatusEnum_InstallFailed = 3;</code>
     */
    const PackageStatusEnum_InstallFailed = 3;
    /**
     * Agent is currently downloading the package.
     * server_offered_hash field MUST be set to indicate the version that the
     * Agent is installing. The error_message field MUST NOT be set.
     * Status: [Development]
     *
     * Generated from protobuf enum <code>PackageStatusEnum_Downloading = 4;</code>
     */
    const PackageStatusEnum_Downloading = 4;

    private static $valueToName = [
        self::PackageStatusEnum_Installed => 'PackageStatusEnum_Installed',
        self::PackageStatusEnum_InstallPending => 'PackageStatusEnum_InstallPending',
        self::PackageStatusEnum_Installing => 'PackageStatusEnum_Installing',
        self::PackageStatusEnum_InstallFailed => 'PackageStatusEnum_InstallFailed',
        self::PackageStatusEnum_Downloading => 'PackageStatusEnum_Downloading',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

