<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The PackageStatuses message describes the status of all packages that the Agent
 * has or was offered.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.PackageStatuses</code>
 */
class PackageStatuses extends \Google\Protobuf\Internal\Message
{
    /**
     * A map of PackageStatus messages, where the keys are package names.
     * The key MUST match the name field of PackageStatus message.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.PackageStatus> packages = 1;</code>
     */
    private $packages;
    /**
     * The aggregate hash of all packages that this Agent previously received from the
     * Server via PackagesAvailable message.
     * The Server SHOULD compare this hash to the aggregate hash of all packages that
     * it has for this Agent and if the hashes are different the Server SHOULD send
     * an PackagesAvailable message to the Agent.
     *
     * Generated from protobuf field <code>bytes server_provided_all_packages_hash = 2;</code>
     */
    protected $server_provided_all_packages_hash = '';
    /**
     * This field is set if the Agent encountered an error when processing the
     * PackagesAvailable message and that error is not related to any particular single
     * package.
     * The field must be unset is there were no processing errors.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $packages
     *           A map of PackageStatus messages, where the keys are package names.
     *           The key MUST match the name field of PackageStatus message.
     *     @type string $server_provided_all_packages_hash
     *           The aggregate hash of all packages that this Agent previously received from the
     *           Server via PackagesAvailable message.
     *           The Server SHOULD compare this hash to the aggregate hash of all packages that
     *           it has for this Agent and if the hashes are different the Server SHOULD send
     *           an PackagesAvailable message to the Agent.
     *     @type string $error_message
     *           This field is set if the Agent encountered an error when processing the
     *           PackagesAvailable message and that error is not related to any particular single
     *           package.
     *           The field must be unset is there were no processing errors.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A map of PackageStatus messages, where the keys are package names.
     * The key MUST match the name field of PackageStatus message.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.PackageStatus> packages = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * A map of PackageStatus messages, where the keys are package names.
     * The key MUST match the name field of PackageStatus message.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.PackageStatus> packages = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPackages($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \GeneratedForElasticOTelTests\OpampProto\PackageStatus::class);
        $this->packages = $arr;

        return $this;
    }

    /**
     * The aggregate hash of all packages that this Agent previously received from the
     * Server via PackagesAvailable message.
     * The Server SHOULD compare this hash to the aggregate hash of all packages that
     * it has for this Agent and if the hashes are different the Server SHOULD send
     * an PackagesAvailable message to the Agent.
     *
     * Generated from protobuf field <code>bytes server_provided_all_packages_hash = 2;</code>
     * @return string
     */
    public function getServerProvidedAllPackagesHash()
    {
        return $this->server_provided_all_packages_hash;
    }

    /**
     * The aggregate hash of all packages that this Agent previously received from the
     * Server via PackagesAvailable message.
     * The Server SHOULD compare this hash to the aggregate hash of all packages that
     * it has for this Agent and if the hashes are different the Server SHOULD send
     * an PackagesAvailable message to the Agent.
     *
     * Generated from protobuf field <code>bytes server_provided_all_packages_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerProvidedAllPackagesHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->server_provided_all_packages_hash = $var;

        return $this;
    }

    /**
     * This field is set if the Agent encountered an error when processing the
     * PackagesAvailable message and that error is not related to any particular single
     * package.
     * The field must be unset is there were no processing errors.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * This field is set if the Agent encountered an error when processing the
     * PackagesAvailable message and that error is not related to any particular single
     * package.
     * The field must be unset is there were no processing errors.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

