<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Each Agent is composed of one or more packages. A package has a name and
 * content stored in a file. The content of the files, functionality
 * provided by the packages, how they are stored and used by the Agent side is Agent
 * type-specific and is outside the concerns of the OpAMP protocol.
 * If the Agent does not have an installed package with the specified name then
 * it SHOULD download it from the specified URL and install it.
 * If the Agent already has an installed package with the specified name
 * but with a different hash then the Agent SHOULD download and
 * install the package again, since it is a different version of the same package.
 * If the Agent has an installed package with the specified name and the same
 * hash then the Agent does not need to do anything, it already
 * has the right version of the package.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.PackageAvailable</code>
 */
class PackageAvailable extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.opamp.proto.PackageType type = 1;</code>
     */
    protected $type = 0;
    /**
     * The package version that is available on the Server side. The Agent may for
     * example use this information to avoid downloading a package that was previously
     * already downloaded and failed to install.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * The downloadable file of the package.
     *
     * Generated from protobuf field <code>.opamp.proto.DownloadableFile file = 3;</code>
     */
    protected $file = null;
    /**
     * The hash of the package. SHOULD be calculated based on all other fields of the
     * PackageAvailable message and content of the file of the package. The hash is
     * used by the Agent to determine if the package it has is different from the
     * package the Server is offering.
     *
     * Generated from protobuf field <code>bytes hash = 4;</code>
     */
    protected $hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $version
     *           The package version that is available on the Server side. The Agent may for
     *           example use this information to avoid downloading a package that was previously
     *           already downloaded and failed to install.
     *     @type \ElasticOTelTests\Generated\OpampProto\DownloadableFile $file
     *           The downloadable file of the package.
     *     @type string $hash
     *           The hash of the package. SHOULD be calculated based on all other fields of the
     *           PackageAvailable message and content of the file of the package. The hash is
     *           used by the Agent to determine if the package it has is different from the
     *           package the Server is offering.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.PackageType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.PackageType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \ElasticOTelTests\Generated\OpampProto\PackageType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * The package version that is available on the Server side. The Agent may for
     * example use this information to avoid downloading a package that was previously
     * already downloaded and failed to install.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * The package version that is available on the Server side. The Agent may for
     * example use this information to avoid downloading a package that was previously
     * already downloaded and failed to install.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * The downloadable file of the package.
     *
     * Generated from protobuf field <code>.opamp.proto.DownloadableFile file = 3;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\DownloadableFile|null
     */
    public function getFile()
    {
        return $this->file;
    }

    public function hasFile()
    {
        return isset($this->file);
    }

    public function clearFile()
    {
        unset($this->file);
    }

    /**
     * The downloadable file of the package.
     *
     * Generated from protobuf field <code>.opamp.proto.DownloadableFile file = 3;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\DownloadableFile $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\DownloadableFile::class);
        $this->file = $var;

        return $this;
    }

    /**
     * The hash of the package. SHOULD be calculated based on all other fields of the
     * PackageAvailable message and content of the file of the package. The hash is
     * used by the Agent to determine if the package it has is different from the
     * package the Server is offering.
     *
     * Generated from protobuf field <code>bytes hash = 4;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * The hash of the package. SHOULD be calculated based on all other fields of the
     * PackageAvailable message and content of the file of the package. The hash is
     * used by the Agent to determine if the package it has is different from the
     * package the Server is offering.
     *
     * Generated from protobuf field <code>bytes hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

}

