<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.ProxyConnectionSettings</code>
 */
class ProxyConnectionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * A URL, host:port or some other destination specifier.
     *
     * Generated from protobuf field <code>string url = 1;</code>
     */
    protected $url = '';
    /**
     * Optional headers to send to proxies during CONNECT requests.
     * These headers can be ignored for non-HTTP based proxies.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers connect_headers = 2;</code>
     */
    protected $connect_headers = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *           A URL, host:port or some other destination specifier.
     *     @type \GeneratedForElasticOTelTests\OpampProto\Headers $connect_headers
     *           Optional headers to send to proxies during CONNECT requests.
     *           These headers can be ignored for non-HTTP based proxies.
     *           For example:
     *           key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A URL, host:port or some other destination specifier.
     *
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * A URL, host:port or some other destination specifier.
     *
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Optional headers to send to proxies during CONNECT requests.
     * These headers can be ignored for non-HTTP based proxies.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers connect_headers = 2;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\Headers|null
     */
    public function getConnectHeaders()
    {
        return $this->connect_headers;
    }

    public function hasConnectHeaders()
    {
        return isset($this->connect_headers);
    }

    public function clearConnectHeaders()
    {
        unset($this->connect_headers);
    }

    /**
     * Optional headers to send to proxies during CONNECT requests.
     * These headers can be ignored for non-HTTP based proxies.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers connect_headers = 2;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\Headers $var
     * @return $this
     */
    public function setConnectHeaders($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\Headers::class);
        $this->connect_headers = $var;

        return $this;
    }

}

