<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.RetryInfo</code>
 */
class RetryInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 retry_after_nanoseconds = 1;</code>
     */
    protected $retry_after_nanoseconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $retry_after_nanoseconds
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 retry_after_nanoseconds = 1;</code>
     * @return int|string
     */
    public function getRetryAfterNanoseconds()
    {
        return $this->retry_after_nanoseconds;
    }

    /**
     * Generated from protobuf field <code>uint64 retry_after_nanoseconds = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRetryAfterNanoseconds($var)
    {
        GPBUtil::checkUint64($var);
        $this->retry_after_nanoseconds = $var;

        return $this;
    }

}

