<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.ServerToAgent</code>
 */
class ServerToAgent extends \Google\Protobuf\Internal\Message
{
    /**
     * Agent instance uid. MUST match the instance_uid field in AgentToServer message.
     * Used for multiplexing messages from/to multiple agents using one message stream.
     *
     * Generated from protobuf field <code>bytes instance_uid = 1;</code>
     */
    protected $instance_uid = '';
    /**
     * error_response is set if the Server wants to indicate that something went wrong
     * during processing of an AgentToServer message. If error_response is set then
     * all other fields below must be unset and vice versa, if any of the fields below is
     * set then error_response must be unset.
     *
     * Generated from protobuf field <code>.opamp.proto.ServerErrorResponse error_response = 2;</code>
     */
    protected $error_response = null;
    /**
     * remote_config field is set when the Server has a remote config offer for the Agent.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentRemoteConfig remote_config = 3;</code>
     */
    protected $remote_config = null;
    /**
     * This field is set when the Server wants the Agent to change one or more
     * of its client connection settings (destination, headers, certificate, etc).
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsOffers connection_settings = 4;</code>
     */
    protected $connection_settings = null;
    /**
     * This field is set when the Server has packages to offer to the Agent.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.PackagesAvailable packages_available = 5;</code>
     */
    protected $packages_available = null;
    /**
     * Bit flags as defined by ServerToAgentFlags bit masks.
     *
     * Generated from protobuf field <code>uint64 flags = 6;</code>
     */
    protected $flags = 0;
    /**
     * Bitmask of flags defined by ServerCapabilities enum.
     * All bits that are not defined in ServerCapabilities enum MUST be set to 0
     * by the Server. This allows extending the protocol and the ServerCapabilities
     * enum in the future such that old Servers automatically report that they
     * don't support the new capability.
     * This field MUST be set in the first ServerToAgent sent by the Server and MAY
     * be omitted in subsequent ServerToAgent messages by setting it to
     * UnspecifiedServerCapability value.
     *
     * Generated from protobuf field <code>uint64 capabilities = 7;</code>
     */
    protected $capabilities = 0;
    /**
     * Properties related to identification of the Agent, which can be overridden
     * by the Server if needed.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentIdentification agent_identification = 8;</code>
     */
    protected $agent_identification = null;
    /**
     * Allows the Server to instruct the Agent to perform a command, e.g. RESTART. This field should not be specified
     * with fields other than instance_uid and capabilities. If specified, other fields will be ignored and the command
     * will be performed.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ServerToAgentCommand command = 9;</code>
     */
    protected $command = null;
    /**
     * A message indicating custom capabilities supported by the Server.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomCapabilities custom_capabilities = 10;</code>
     */
    protected $custom_capabilities = null;
    /**
     * A custom message sent from the Server to an Agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomMessage custom_message = 11;</code>
     */
    protected $custom_message = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $instance_uid
     *           Agent instance uid. MUST match the instance_uid field in AgentToServer message.
     *           Used for multiplexing messages from/to multiple agents using one message stream.
     *     @type \GeneratedForElasticOTelTests\OpampProto\ServerErrorResponse $error_response
     *           error_response is set if the Server wants to indicate that something went wrong
     *           during processing of an AgentToServer message. If error_response is set then
     *           all other fields below must be unset and vice versa, if any of the fields below is
     *           set then error_response must be unset.
     *     @type \GeneratedForElasticOTelTests\OpampProto\AgentRemoteConfig $remote_config
     *           remote_config field is set when the Server has a remote config offer for the Agent.
     *     @type \GeneratedForElasticOTelTests\OpampProto\ConnectionSettingsOffers $connection_settings
     *           This field is set when the Server wants the Agent to change one or more
     *           of its client connection settings (destination, headers, certificate, etc).
     *           Status: [Beta]
     *     @type \GeneratedForElasticOTelTests\OpampProto\PackagesAvailable $packages_available
     *           This field is set when the Server has packages to offer to the Agent.
     *           Status: [Beta]
     *     @type int|string $flags
     *           Bit flags as defined by ServerToAgentFlags bit masks.
     *     @type int|string $capabilities
     *           Bitmask of flags defined by ServerCapabilities enum.
     *           All bits that are not defined in ServerCapabilities enum MUST be set to 0
     *           by the Server. This allows extending the protocol and the ServerCapabilities
     *           enum in the future such that old Servers automatically report that they
     *           don't support the new capability.
     *           This field MUST be set in the first ServerToAgent sent by the Server and MAY
     *           be omitted in subsequent ServerToAgent messages by setting it to
     *           UnspecifiedServerCapability value.
     *     @type \GeneratedForElasticOTelTests\OpampProto\AgentIdentification $agent_identification
     *           Properties related to identification of the Agent, which can be overridden
     *           by the Server if needed.
     *     @type \GeneratedForElasticOTelTests\OpampProto\ServerToAgentCommand $command
     *           Allows the Server to instruct the Agent to perform a command, e.g. RESTART. This field should not be specified
     *           with fields other than instance_uid and capabilities. If specified, other fields will be ignored and the command
     *           will be performed.
     *           Status: [Beta]
     *     @type \GeneratedForElasticOTelTests\OpampProto\CustomCapabilities $custom_capabilities
     *           A message indicating custom capabilities supported by the Server.
     *           Status: [Development]
     *     @type \GeneratedForElasticOTelTests\OpampProto\CustomMessage $custom_message
     *           A custom message sent from the Server to an Agent.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Agent instance uid. MUST match the instance_uid field in AgentToServer message.
     * Used for multiplexing messages from/to multiple agents using one message stream.
     *
     * Generated from protobuf field <code>bytes instance_uid = 1;</code>
     * @return string
     */
    public function getInstanceUid()
    {
        return $this->instance_uid;
    }

    /**
     * Agent instance uid. MUST match the instance_uid field in AgentToServer message.
     * Used for multiplexing messages from/to multiple agents using one message stream.
     *
     * Generated from protobuf field <code>bytes instance_uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceUid($var)
    {
        GPBUtil::checkString($var, False);
        $this->instance_uid = $var;

        return $this;
    }

    /**
     * error_response is set if the Server wants to indicate that something went wrong
     * during processing of an AgentToServer message. If error_response is set then
     * all other fields below must be unset and vice versa, if any of the fields below is
     * set then error_response must be unset.
     *
     * Generated from protobuf field <code>.opamp.proto.ServerErrorResponse error_response = 2;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\ServerErrorResponse|null
     */
    public function getErrorResponse()
    {
        return $this->error_response;
    }

    public function hasErrorResponse()
    {
        return isset($this->error_response);
    }

    public function clearErrorResponse()
    {
        unset($this->error_response);
    }

    /**
     * error_response is set if the Server wants to indicate that something went wrong
     * during processing of an AgentToServer message. If error_response is set then
     * all other fields below must be unset and vice versa, if any of the fields below is
     * set then error_response must be unset.
     *
     * Generated from protobuf field <code>.opamp.proto.ServerErrorResponse error_response = 2;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\ServerErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\ServerErrorResponse::class);
        $this->error_response = $var;

        return $this;
    }

    /**
     * remote_config field is set when the Server has a remote config offer for the Agent.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentRemoteConfig remote_config = 3;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\AgentRemoteConfig|null
     */
    public function getRemoteConfig()
    {
        return $this->remote_config;
    }

    public function hasRemoteConfig()
    {
        return isset($this->remote_config);
    }

    public function clearRemoteConfig()
    {
        unset($this->remote_config);
    }

    /**
     * remote_config field is set when the Server has a remote config offer for the Agent.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentRemoteConfig remote_config = 3;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\AgentRemoteConfig $var
     * @return $this
     */
    public function setRemoteConfig($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\AgentRemoteConfig::class);
        $this->remote_config = $var;

        return $this;
    }

    /**
     * This field is set when the Server wants the Agent to change one or more
     * of its client connection settings (destination, headers, certificate, etc).
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsOffers connection_settings = 4;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\ConnectionSettingsOffers|null
     */
    public function getConnectionSettings()
    {
        return $this->connection_settings;
    }

    public function hasConnectionSettings()
    {
        return isset($this->connection_settings);
    }

    public function clearConnectionSettings()
    {
        unset($this->connection_settings);
    }

    /**
     * This field is set when the Server wants the Agent to change one or more
     * of its client connection settings (destination, headers, certificate, etc).
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ConnectionSettingsOffers connection_settings = 4;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\ConnectionSettingsOffers $var
     * @return $this
     */
    public function setConnectionSettings($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\ConnectionSettingsOffers::class);
        $this->connection_settings = $var;

        return $this;
    }

    /**
     * This field is set when the Server has packages to offer to the Agent.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.PackagesAvailable packages_available = 5;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\PackagesAvailable|null
     */
    public function getPackagesAvailable()
    {
        return $this->packages_available;
    }

    public function hasPackagesAvailable()
    {
        return isset($this->packages_available);
    }

    public function clearPackagesAvailable()
    {
        unset($this->packages_available);
    }

    /**
     * This field is set when the Server has packages to offer to the Agent.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.PackagesAvailable packages_available = 5;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\PackagesAvailable $var
     * @return $this
     */
    public function setPackagesAvailable($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\PackagesAvailable::class);
        $this->packages_available = $var;

        return $this;
    }

    /**
     * Bit flags as defined by ServerToAgentFlags bit masks.
     *
     * Generated from protobuf field <code>uint64 flags = 6;</code>
     * @return int|string
     */
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Bit flags as defined by ServerToAgentFlags bit masks.
     *
     * Generated from protobuf field <code>uint64 flags = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlags($var)
    {
        GPBUtil::checkUint64($var);
        $this->flags = $var;

        return $this;
    }

    /**
     * Bitmask of flags defined by ServerCapabilities enum.
     * All bits that are not defined in ServerCapabilities enum MUST be set to 0
     * by the Server. This allows extending the protocol and the ServerCapabilities
     * enum in the future such that old Servers automatically report that they
     * don't support the new capability.
     * This field MUST be set in the first ServerToAgent sent by the Server and MAY
     * be omitted in subsequent ServerToAgent messages by setting it to
     * UnspecifiedServerCapability value.
     *
     * Generated from protobuf field <code>uint64 capabilities = 7;</code>
     * @return int|string
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * Bitmask of flags defined by ServerCapabilities enum.
     * All bits that are not defined in ServerCapabilities enum MUST be set to 0
     * by the Server. This allows extending the protocol and the ServerCapabilities
     * enum in the future such that old Servers automatically report that they
     * don't support the new capability.
     * This field MUST be set in the first ServerToAgent sent by the Server and MAY
     * be omitted in subsequent ServerToAgent messages by setting it to
     * UnspecifiedServerCapability value.
     *
     * Generated from protobuf field <code>uint64 capabilities = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCapabilities($var)
    {
        GPBUtil::checkUint64($var);
        $this->capabilities = $var;

        return $this;
    }

    /**
     * Properties related to identification of the Agent, which can be overridden
     * by the Server if needed.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentIdentification agent_identification = 8;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\AgentIdentification|null
     */
    public function getAgentIdentification()
    {
        return $this->agent_identification;
    }

    public function hasAgentIdentification()
    {
        return isset($this->agent_identification);
    }

    public function clearAgentIdentification()
    {
        unset($this->agent_identification);
    }

    /**
     * Properties related to identification of the Agent, which can be overridden
     * by the Server if needed.
     *
     * Generated from protobuf field <code>.opamp.proto.AgentIdentification agent_identification = 8;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\AgentIdentification $var
     * @return $this
     */
    public function setAgentIdentification($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\AgentIdentification::class);
        $this->agent_identification = $var;

        return $this;
    }

    /**
     * Allows the Server to instruct the Agent to perform a command, e.g. RESTART. This field should not be specified
     * with fields other than instance_uid and capabilities. If specified, other fields will be ignored and the command
     * will be performed.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ServerToAgentCommand command = 9;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\ServerToAgentCommand|null
     */
    public function getCommand()
    {
        return $this->command;
    }

    public function hasCommand()
    {
        return isset($this->command);
    }

    public function clearCommand()
    {
        unset($this->command);
    }

    /**
     * Allows the Server to instruct the Agent to perform a command, e.g. RESTART. This field should not be specified
     * with fields other than instance_uid and capabilities. If specified, other fields will be ignored and the command
     * will be performed.
     * Status: [Beta]
     *
     * Generated from protobuf field <code>.opamp.proto.ServerToAgentCommand command = 9;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\ServerToAgentCommand $var
     * @return $this
     */
    public function setCommand($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\ServerToAgentCommand::class);
        $this->command = $var;

        return $this;
    }

    /**
     * A message indicating custom capabilities supported by the Server.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomCapabilities custom_capabilities = 10;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\CustomCapabilities|null
     */
    public function getCustomCapabilities()
    {
        return $this->custom_capabilities;
    }

    public function hasCustomCapabilities()
    {
        return isset($this->custom_capabilities);
    }

    public function clearCustomCapabilities()
    {
        unset($this->custom_capabilities);
    }

    /**
     * A message indicating custom capabilities supported by the Server.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomCapabilities custom_capabilities = 10;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\CustomCapabilities $var
     * @return $this
     */
    public function setCustomCapabilities($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\CustomCapabilities::class);
        $this->custom_capabilities = $var;

        return $this;
    }

    /**
     * A custom message sent from the Server to an Agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomMessage custom_message = 11;</code>
     * @return \GeneratedForElasticOTelTests\OpampProto\CustomMessage|null
     */
    public function getCustomMessage()
    {
        return $this->custom_message;
    }

    public function hasCustomMessage()
    {
        return isset($this->custom_message);
    }

    public function clearCustomMessage()
    {
        unset($this->custom_message);
    }

    /**
     * A custom message sent from the Server to an Agent.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.CustomMessage custom_message = 11;</code>
     * @param \GeneratedForElasticOTelTests\OpampProto\CustomMessage $var
     * @return $this
     */
    public function setCustomMessage($var)
    {
        GPBUtil::checkMessage($var, \GeneratedForElasticOTelTests\OpampProto\CustomMessage::class);
        $this->custom_message = $var;

        return $this;
    }

}

