<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use UnexpectedValueException;

/**
 * Protobuf type <code>opamp.proto.ServerToAgentFlags</code>
 */
class ServerToAgentFlags
{
    /**
     * Generated from protobuf enum <code>ServerToAgentFlags_Unspecified = 0;</code>
     */
    const ServerToAgentFlags_Unspecified = 0;
    /**
     * ReportFullState flag can be used by the Server if the Agent did not include the
     * particular bit of information in the last status report (which is an allowed
     * optimization) but the Server detects that it does not have it (e.g. was
     * restarted and lost state). The detection happens using
     * AgentToServer.sequence_num values.
     * The Server asks the Agent to report full status.
     *
     * Generated from protobuf enum <code>ServerToAgentFlags_ReportFullState = 1;</code>
     */
    const ServerToAgentFlags_ReportFullState = 1;
    /**
     * ReportAvailableComponents flag can be used by the server if the Agent did
     * not include the full AvailableComponents message, but only the hash.
     * If this flag is specified, the agent will populate available_components.components
     * with a full description of the agent's components.
     * Status: [Development]
     *
     * Generated from protobuf enum <code>ServerToAgentFlags_ReportAvailableComponents = 2;</code>
     */
    const ServerToAgentFlags_ReportAvailableComponents = 2;

    private static $valueToName = [
        self::ServerToAgentFlags_Unspecified => 'ServerToAgentFlags_Unspecified',
        self::ServerToAgentFlags_ReportFullState => 'ServerToAgentFlags_ReportFullState',
        self::ServerToAgentFlags_ReportAvailableComponents => 'ServerToAgentFlags_ReportAvailableComponents',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

