<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use UnexpectedValueException;

/**
 * Protobuf type <code>opamp.proto.ServerCapabilities</code>
 */
class ServerCapabilities
{
    /**
     * The capabilities field is unspecified.
     *
     * Generated from protobuf enum <code>ServerCapabilities_Unspecified = 0;</code>
     */
    const ServerCapabilities_Unspecified = 0;
    /**
     * The Server can accept status reports. This bit MUST be set, since all Server
     * MUST be able to accept status reports.
     *
     * Generated from protobuf enum <code>ServerCapabilities_AcceptsStatus = 1;</code>
     */
    const ServerCapabilities_AcceptsStatus = 1;
    /**
     * The Server can offer remote configuration to the Agent.
     *
     * Generated from protobuf enum <code>ServerCapabilities_OffersRemoteConfig = 2;</code>
     */
    const ServerCapabilities_OffersRemoteConfig = 2;
    /**
     * The Server can accept EffectiveConfig in AgentToServer.
     *
     * Generated from protobuf enum <code>ServerCapabilities_AcceptsEffectiveConfig = 4;</code>
     */
    const ServerCapabilities_AcceptsEffectiveConfig = 4;
    /**
     * The Server can offer Packages.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>ServerCapabilities_OffersPackages = 8;</code>
     */
    const ServerCapabilities_OffersPackages = 8;
    /**
     * The Server can accept Packages status.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>ServerCapabilities_AcceptsPackagesStatus = 16;</code>
     */
    const ServerCapabilities_AcceptsPackagesStatus = 16;
    /**
     * The Server can offer connection settings.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>ServerCapabilities_OffersConnectionSettings = 32;</code>
     */
    const ServerCapabilities_OffersConnectionSettings = 32;
    /**
     * The Server can accept ConnectionSettingsRequest and respond with an offer.
     * Status: [Development]
     *
     * Generated from protobuf enum <code>ServerCapabilities_AcceptsConnectionSettingsRequest = 64;</code>
     */
    const ServerCapabilities_AcceptsConnectionSettingsRequest = 64;

    private static $valueToName = [
        self::ServerCapabilities_Unspecified => 'ServerCapabilities_Unspecified',
        self::ServerCapabilities_AcceptsStatus => 'ServerCapabilities_AcceptsStatus',
        self::ServerCapabilities_OffersRemoteConfig => 'ServerCapabilities_OffersRemoteConfig',
        self::ServerCapabilities_AcceptsEffectiveConfig => 'ServerCapabilities_AcceptsEffectiveConfig',
        self::ServerCapabilities_OffersPackages => 'ServerCapabilities_OffersPackages',
        self::ServerCapabilities_AcceptsPackagesStatus => 'ServerCapabilities_AcceptsPackagesStatus',
        self::ServerCapabilities_OffersConnectionSettings => 'ServerCapabilities_OffersConnectionSettings',
        self::ServerCapabilities_AcceptsConnectionSettingsRequest => 'ServerCapabilities_AcceptsConnectionSettingsRequest',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

