<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.ServerErrorResponse</code>
 */
class ServerErrorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.opamp.proto.ServerErrorResponseType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Error message in the string form, typically human readable.
     *
     * Generated from protobuf field <code>string error_message = 2;</code>
     */
    protected $error_message = '';
    protected $Details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $error_message
     *           Error message in the string form, typically human readable.
     *     @type \ElasticOTelTests\Generated\OpampProto\RetryInfo $retry_info
     *           Additional information about retrying if type==UNAVAILABLE.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.ServerErrorResponseType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.ServerErrorResponseType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \ElasticOTelTests\Generated\OpampProto\ServerErrorResponseType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Error message in the string form, typically human readable.
     *
     * Generated from protobuf field <code>string error_message = 2;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Error message in the string form, typically human readable.
     *
     * Generated from protobuf field <code>string error_message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Additional information about retrying if type==UNAVAILABLE.
     *
     * Generated from protobuf field <code>.opamp.proto.RetryInfo retry_info = 3;</code>
     * @return \ElasticOTelTests\Generated\OpampProto\RetryInfo|null
     */
    public function getRetryInfo()
    {
        return $this->readOneof(3);
    }

    public function hasRetryInfo()
    {
        return $this->hasOneof(3);
    }

    /**
     * Additional information about retrying if type==UNAVAILABLE.
     *
     * Generated from protobuf field <code>.opamp.proto.RetryInfo retry_info = 3;</code>
     * @param \ElasticOTelTests\Generated\OpampProto\RetryInfo $var
     * @return $this
     */
    public function setRetryInfo($var)
    {
        GPBUtil::checkMessage($var, \ElasticOTelTests\Generated\OpampProto\RetryInfo::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getDetails()
    {
        return $this->whichOneof("Details");
    }

}

