<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace ElasticOTelTests\Generated\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.TLSCertificate</code>
 */
class TLSCertificate extends \Google\Protobuf\Internal\Message
{
    /**
     * PEM-encoded certificate. Required.
     *
     * Generated from protobuf field <code>bytes cert = 1;</code>
     */
    protected $cert = '';
    /**
     * PEM-encoded private key of the certificate. Required.
     *
     * Generated from protobuf field <code>bytes private_key = 2;</code>
     */
    protected $private_key = '';
    /**
     * PEM-encoded certificate of the signing CA.
     * Optional. MUST be specified if the certificate is CA-signed.
     * Can be stored by TLS-terminating intermediary proxies in order to verify
     * the connecting client's certificate in the future.
     * It is not recommended that the Agent accepts this CA as an authority for
     * any purposes.
     *
     * Generated from protobuf field <code>bytes ca_cert = 3;</code>
     */
    protected $ca_cert = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cert
     *           PEM-encoded certificate. Required.
     *     @type string $private_key
     *           PEM-encoded private key of the certificate. Required.
     *     @type string $ca_cert
     *           PEM-encoded certificate of the signing CA.
     *           Optional. MUST be specified if the certificate is CA-signed.
     *           Can be stored by TLS-terminating intermediary proxies in order to verify
     *           the connecting client's certificate in the future.
     *           It is not recommended that the Agent accepts this CA as an authority for
     *           any purposes.
     * }
     */
    public function __construct($data = NULL) {
        \ElasticOTelTests\Generated\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * PEM-encoded certificate. Required.
     *
     * Generated from protobuf field <code>bytes cert = 1;</code>
     * @return string
     */
    public function getCert()
    {
        return $this->cert;
    }

    /**
     * PEM-encoded certificate. Required.
     *
     * Generated from protobuf field <code>bytes cert = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCert($var)
    {
        GPBUtil::checkString($var, False);
        $this->cert = $var;

        return $this;
    }

    /**
     * PEM-encoded private key of the certificate. Required.
     *
     * Generated from protobuf field <code>bytes private_key = 2;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * PEM-encoded private key of the certificate. Required.
     *
     * Generated from protobuf field <code>bytes private_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->private_key = $var;

        return $this;
    }

    /**
     * PEM-encoded certificate of the signing CA.
     * Optional. MUST be specified if the certificate is CA-signed.
     * Can be stored by TLS-terminating intermediary proxies in order to verify
     * the connecting client's certificate in the future.
     * It is not recommended that the Agent accepts this CA as an authority for
     * any purposes.
     *
     * Generated from protobuf field <code>bytes ca_cert = 3;</code>
     * @return string
     */
    public function getCaCert()
    {
        return $this->ca_cert;
    }

    /**
     * PEM-encoded certificate of the signing CA.
     * Optional. MUST be specified if the certificate is CA-signed.
     * Can be stored by TLS-terminating intermediary proxies in order to verify
     * the connecting client's certificate in the future.
     * It is not recommended that the Agent accepts this CA as an authority for
     * any purposes.
     *
     * Generated from protobuf field <code>bytes ca_cert = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCaCert($var)
    {
        GPBUtil::checkString($var, False);
        $this->ca_cert = $var;

        return $this;
    }

}

