<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace GeneratedForElasticOTelTests\OpampProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TLSConnectionSettings are optional connection settings that can be passed to
 * the client in order to specify TLS configuration.
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.TLSConnectionSettings</code>
 */
class TLSConnectionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Provides CA cert contents as a string.
     *
     * Generated from protobuf field <code>string ca_pem_contents = 1;</code>
     */
    protected $ca_pem_contents = '';
    /**
     * Load system CA pool alongside any passed CAs.
     *
     * Generated from protobuf field <code>bool include_system_ca_certs_pool = 2;</code>
     */
    protected $include_system_ca_certs_pool = false;
    /**
     * skip certificate verification.
     *
     * Generated from protobuf field <code>bool insecure_skip_verify = 3;</code>
     */
    protected $insecure_skip_verify = false;
    /**
     * Miniumum accepted TLS version; default "1.2".
     *
     * Generated from protobuf field <code>string min_version = 4;</code>
     */
    protected $min_version = '';
    /**
     * Maxiumum accepted TLS version; default "".
     *
     * Generated from protobuf field <code>string max_version = 5;</code>
     */
    protected $max_version = '';
    /**
     * Explicit list of cipher suites.
     *
     * Generated from protobuf field <code>repeated string cipher_suites = 6;</code>
     */
    private $cipher_suites;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ca_pem_contents
     *           Provides CA cert contents as a string.
     *     @type bool $include_system_ca_certs_pool
     *           Load system CA pool alongside any passed CAs.
     *     @type bool $insecure_skip_verify
     *           skip certificate verification.
     *     @type string $min_version
     *           Miniumum accepted TLS version; default "1.2".
     *     @type string $max_version
     *           Maxiumum accepted TLS version; default "".
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $cipher_suites
     *           Explicit list of cipher suites.
     * }
     */
    public function __construct($data = NULL) {
        \GeneratedForElasticOTelTests\OpampProto\Metadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Provides CA cert contents as a string.
     *
     * Generated from protobuf field <code>string ca_pem_contents = 1;</code>
     * @return string
     */
    public function getCaPemContents()
    {
        return $this->ca_pem_contents;
    }

    /**
     * Provides CA cert contents as a string.
     *
     * Generated from protobuf field <code>string ca_pem_contents = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCaPemContents($var)
    {
        GPBUtil::checkString($var, True);
        $this->ca_pem_contents = $var;

        return $this;
    }

    /**
     * Load system CA pool alongside any passed CAs.
     *
     * Generated from protobuf field <code>bool include_system_ca_certs_pool = 2;</code>
     * @return bool
     */
    public function getIncludeSystemCaCertsPool()
    {
        return $this->include_system_ca_certs_pool;
    }

    /**
     * Load system CA pool alongside any passed CAs.
     *
     * Generated from protobuf field <code>bool include_system_ca_certs_pool = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeSystemCaCertsPool($var)
    {
        GPBUtil::checkBool($var);
        $this->include_system_ca_certs_pool = $var;

        return $this;
    }

    /**
     * skip certificate verification.
     *
     * Generated from protobuf field <code>bool insecure_skip_verify = 3;</code>
     * @return bool
     */
    public function getInsecureSkipVerify()
    {
        return $this->insecure_skip_verify;
    }

    /**
     * skip certificate verification.
     *
     * Generated from protobuf field <code>bool insecure_skip_verify = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setInsecureSkipVerify($var)
    {
        GPBUtil::checkBool($var);
        $this->insecure_skip_verify = $var;

        return $this;
    }

    /**
     * Miniumum accepted TLS version; default "1.2".
     *
     * Generated from protobuf field <code>string min_version = 4;</code>
     * @return string
     */
    public function getMinVersion()
    {
        return $this->min_version;
    }

    /**
     * Miniumum accepted TLS version; default "1.2".
     *
     * Generated from protobuf field <code>string min_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMinVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->min_version = $var;

        return $this;
    }

    /**
     * Maxiumum accepted TLS version; default "".
     *
     * Generated from protobuf field <code>string max_version = 5;</code>
     * @return string
     */
    public function getMaxVersion()
    {
        return $this->max_version;
    }

    /**
     * Maxiumum accepted TLS version; default "".
     *
     * Generated from protobuf field <code>string max_version = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_version = $var;

        return $this;
    }

    /**
     * Explicit list of cipher suites.
     *
     * Generated from protobuf field <code>repeated string cipher_suites = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCipherSuites()
    {
        return $this->cipher_suites;
    }

    /**
     * Explicit list of cipher suites.
     *
     * Generated from protobuf field <code>repeated string cipher_suites = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCipherSuites($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cipher_suites = $arr;

        return $this;
    }

}

