ARG PHP_VERSION
FROM php:${PHP_VERSION}-cli-alpine

RUN ls -1 /etc/*release | xargs -i sh -c 'echo {} && cat {}'

RUN apk update \
    && apk add \
        bash \
        git \
        libzip-dev \
        logrotate \
        perl-utils \
        postgresql-dev \
        procps \
        rsyslog

RUN docker-php-ext-install \
        mysqli \
        opcache \
        pgsql \
        zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /

ENTRYPOINT exec /read_only_repo_root/tools/test/component/docker_entrypoint.sh
