ARG PHP_VERSION
FROM php:${PHP_VERSION}-cli

RUN ls -1 /etc/*release | xargs -i sh -c 'echo {} && cat {}'

RUN apt-get -qq update \
    && apt-get -qq -y --no-install-recommends install \
        curl \
        gnupg \
        gnupg2 \
        git \
        libcurl4 libcurl4-openssl-dev \
        libsqlite3-dev \
        libzip-dev \
        logrotate \
        procps \
        rsyslog \
        unzip \
        wget \
        zlib1g-dev

RUN docker-php-ext-install \
        curl \
        pdo_sqlite \
        zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

ADD . /repo_root
WORKDIR /repo_root

ENTRYPOINT /repo_root/tools/test/component/docker_entrypoint.sh
