ARG PHP_VERSION
FROM php:${PHP_VERSION}-cli

RUN ls -1 /etc/*release | xargs -i sh -c 'echo {} && cat {}'

RUN apt-get -qq update \
    && apt-get -qq -y --no-install-recommends install \
        git \
        libpq-dev \
        libzip-dev \
        logrotate \
        procps \
        rsync \
        rsyslog

RUN docker-php-ext-install \
        mysqli \
        opcache \
        pgsql \
        zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /

ENTRYPOINT exec /docker_host_repo_root/tools/test/component/docker_entrypoint.sh
