<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>opamp.proto.AgentCapabilities</code>
 */
class AgentCapabilities
{
    /**
     * The capabilities field is unspecified.
     *
     * Generated from protobuf enum <code>AgentCapabilities_Unspecified = 0;</code>
     */
    const AgentCapabilities_Unspecified = 0;
    /**
     * The Agent can report status. This bit MUST be set, since all Agents MUST
     * report status.
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsStatus = 1;</code>
     */
    const AgentCapabilities_ReportsStatus = 1;
    /**
     * The Agent can accept remote configuration from the Server.
     *
     * Generated from protobuf enum <code>AgentCapabilities_AcceptsRemoteConfig = 2;</code>
     */
    const AgentCapabilities_AcceptsRemoteConfig = 2;
    /**
     * The Agent will report EffectiveConfig in AgentToServer.
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsEffectiveConfig = 4;</code>
     */
    const AgentCapabilities_ReportsEffectiveConfig = 4;
    /**
     * The Agent can accept package offers.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_AcceptsPackages = 8;</code>
     */
    const AgentCapabilities_AcceptsPackages = 8;
    /**
     * The Agent can report package status.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsPackageStatuses = 16;</code>
     */
    const AgentCapabilities_ReportsPackageStatuses = 16;
    /**
     * The Agent can report own trace to the destination specified by
     * the Server via ConnectionSettingsOffers.own_traces field.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsOwnTraces = 32;</code>
     */
    const AgentCapabilities_ReportsOwnTraces = 32;
    /**
     * The Agent can report own metrics to the destination specified by
     * the Server via ConnectionSettingsOffers.own_metrics field.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsOwnMetrics = 64;</code>
     */
    const AgentCapabilities_ReportsOwnMetrics = 64;
    /**
     * The Agent can report own logs to the destination specified by
     * the Server via ConnectionSettingsOffers.own_logs field.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsOwnLogs = 128;</code>
     */
    const AgentCapabilities_ReportsOwnLogs = 128;
    /**
     * The can accept connections settings for OpAMP via
     * ConnectionSettingsOffers.opamp field.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_AcceptsOpAMPConnectionSettings = 256;</code>
     */
    const AgentCapabilities_AcceptsOpAMPConnectionSettings = 256;
    /**
     * The can accept connections settings for other destinations via
     * ConnectionSettingsOffers.other_connections field.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_AcceptsOtherConnectionSettings = 512;</code>
     */
    const AgentCapabilities_AcceptsOtherConnectionSettings = 512;
    /**
     * The Agent can accept restart requests.
     * Status: [Beta]
     *
     * Generated from protobuf enum <code>AgentCapabilities_AcceptsRestartCommand = 1024;</code>
     */
    const AgentCapabilities_AcceptsRestartCommand = 1024;
    /**
     * The Agent will report Health via AgentToServer.health field.
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsHealth = 2048;</code>
     */
    const AgentCapabilities_ReportsHealth = 2048;
    /**
     * The Agent will report RemoteConfig status via AgentToServer.remote_config_status field.
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsRemoteConfig = 4096;</code>
     */
    const AgentCapabilities_ReportsRemoteConfig = 4096;
    /**
     * The Agent can report heartbeats.
     * This is specified by the ServerToAgent.OpAMPConnectionSettings.heartbeat_interval_seconds field.
     * If this capability is true, but the Server does not set a heartbeat_interval_seconds field, the
     * Agent should use its own configured interval, which by default will be 30s. The Server may not
     * know the configured interval and should not make assumptions about it.
     * Status: [Development]
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsHeartbeat = 8192;</code>
     */
    const AgentCapabilities_ReportsHeartbeat = 8192;
    /**
     * The agent will report AvailableComponents via the AgentToServer.available_components field.
     * Status: [Development]
     *
     * Generated from protobuf enum <code>AgentCapabilities_ReportsAvailableComponents = 16384;</code>
     */
    const AgentCapabilities_ReportsAvailableComponents = 16384;

    private static $valueToName = [
        self::AgentCapabilities_Unspecified => 'AgentCapabilities_Unspecified',
        self::AgentCapabilities_ReportsStatus => 'AgentCapabilities_ReportsStatus',
        self::AgentCapabilities_AcceptsRemoteConfig => 'AgentCapabilities_AcceptsRemoteConfig',
        self::AgentCapabilities_ReportsEffectiveConfig => 'AgentCapabilities_ReportsEffectiveConfig',
        self::AgentCapabilities_AcceptsPackages => 'AgentCapabilities_AcceptsPackages',
        self::AgentCapabilities_ReportsPackageStatuses => 'AgentCapabilities_ReportsPackageStatuses',
        self::AgentCapabilities_ReportsOwnTraces => 'AgentCapabilities_ReportsOwnTraces',
        self::AgentCapabilities_ReportsOwnMetrics => 'AgentCapabilities_ReportsOwnMetrics',
        self::AgentCapabilities_ReportsOwnLogs => 'AgentCapabilities_ReportsOwnLogs',
        self::AgentCapabilities_AcceptsOpAMPConnectionSettings => 'AgentCapabilities_AcceptsOpAMPConnectionSettings',
        self::AgentCapabilities_AcceptsOtherConnectionSettings => 'AgentCapabilities_AcceptsOtherConnectionSettings',
        self::AgentCapabilities_AcceptsRestartCommand => 'AgentCapabilities_AcceptsRestartCommand',
        self::AgentCapabilities_ReportsHealth => 'AgentCapabilities_ReportsHealth',
        self::AgentCapabilities_ReportsRemoteConfig => 'AgentCapabilities_ReportsRemoteConfig',
        self::AgentCapabilities_ReportsHeartbeat => 'AgentCapabilities_ReportsHeartbeat',
        self::AgentCapabilities_ReportsAvailableComponents => 'AgentCapabilities_ReportsAvailableComponents',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

