<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.AgentConfigFile</code>
 */
class AgentConfigFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Config file or section body. The content, format and encoding depends on the Agent
     * type. The content_type field may optionally describe the MIME type of the body.
     *
     * Generated from protobuf field <code>bytes body = 1;</code>
     */
    protected $body = '';
    /**
     * Optional MIME Content-Type that describes what's in the body field, for
     * example "text/yaml".
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     */
    protected $content_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $body
     *           Config file or section body. The content, format and encoding depends on the Agent
     *           type. The content_type field may optionally describe the MIME type of the body.
     *     @type string $content_type
     *           Optional MIME Content-Type that describes what's in the body field, for
     *           example "text/yaml".
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Config file or section body. The content, format and encoding depends on the Agent
     * type. The content_type field may optionally describe the MIME type of the body.
     *
     * Generated from protobuf field <code>bytes body = 1;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Config file or section body. The content, format and encoding depends on the Agent
     * type. The content_type field may optionally describe the MIME type of the body.
     *
     * Generated from protobuf field <code>bytes body = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * Optional MIME Content-Type that describes what's in the body field, for
     * example "text/yaml".
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Optional MIME Content-Type that describes what's in the body field, for
     * example "text/yaml".
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

}

