<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AvailableComponents contains metadata relating to the components included
 * within the agent.
 * status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.AvailableComponents</code>
 */
class AvailableComponents extends \Google\Protobuf\Internal\Message
{
    /**
     * A map of a unique component ID to details about the component.
     * This may be omitted from the message if the server has not
     * explicitly requested it be sent by setting the ReportAvailableComponents
     * flag in the previous ServerToAgent message.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentDetails> components = 1;</code>
     */
    private $components;
    /**
     * Agent-calculated hash of the components.
     * This hash should be included in every AvailableComponents message.
     *
     * Generated from protobuf field <code>bytes hash = 2;</code>
     */
    protected $hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $components
     *           A map of a unique component ID to details about the component.
     *           This may be omitted from the message if the server has not
     *           explicitly requested it be sent by setting the ReportAvailableComponents
     *           flag in the previous ServerToAgent message.
     *     @type string $hash
     *           Agent-calculated hash of the components.
     *           This hash should be included in every AvailableComponents message.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A map of a unique component ID to details about the component.
     * This may be omitted from the message if the server has not
     * explicitly requested it be sent by setting the ReportAvailableComponents
     * flag in the previous ServerToAgent message.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentDetails> components = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getComponents()
    {
        return $this->components;
    }

    /**
     * A map of a unique component ID to details about the component.
     * This may be omitted from the message if the server has not
     * explicitly requested it be sent by setting the ReportAvailableComponents
     * flag in the previous ServerToAgent message.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.ComponentDetails> components = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setComponents($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opamp\Proto\ComponentDetails::class);
        $this->components = $arr;

        return $this;
    }

    /**
     * Agent-calculated hash of the components.
     * This hash should be included in every AvailableComponents message.
     *
     * Generated from protobuf field <code>bytes hash = 2;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Agent-calculated hash of the components.
     * This hash should be included in every AvailableComponents message.
     *
     * Generated from protobuf field <code>bytes hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

}

