<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.ConnectionSettingsOffers</code>
 */
class ConnectionSettingsOffers extends \Google\Protobuf\Internal\Message
{
    /**
     * Hash of all settings, including settings that may be omitted from this message
     * because they are unchanged.
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    protected $hash = '';
    /**
     * Settings to connect to the OpAMP Server.
     * If this field is not set then the Agent should assume that the settings are
     * unchanged and should continue using existing settings.
     * The Agent MUST verify the offered connection settings by actually connecting
     * before accepting the setting to ensure it does not loose access to the OpAMP
     * Server due to invalid settings.
     *
     * Generated from protobuf field <code>.opamp.proto.OpAMPConnectionSettings opamp = 2;</code>
     */
    protected $opamp = null;
    /**
     * Settings to connect to an OTLP metrics backend to send Agent's own metrics to.
     * If this field is not set then the Agent should assume that the settings
     * are unchanged.
     * Once accepted the Agent should periodically send to the specified destination
     * its own metrics, i.e. metrics of the Agent process and any custom metrics that
     * describe the Agent state.
     * All attributes specified in the identifying_attributes field in AgentDescription
     * message SHOULD be also specified in the Resource of the reported OTLP metrics.
     * Attributes specified in the non_identifying_attributes field in
     * AgentDescription message may be also specified in the Resource of the reported
     * OTLP metrics, in which case they SHOULD have exactly the same values.
     * Process metrics MUST follow the conventions for processes:
     * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_metrics = 3;</code>
     */
    protected $own_metrics = null;
    /**
     * Similar to own_metrics, but for traces.
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_traces = 4;</code>
     */
    protected $own_traces = null;
    /**
     * Similar to own_metrics, but for logs.
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_logs = 5;</code>
     */
    protected $own_logs = null;
    /**
     * Another set of connection settings, with a string name associated with each.
     * How the Agent uses these is Agent-specific. Typically the name represents
     * the name of the destination to connect to (as it is known to the Agent).
     * If this field is not set then the Agent should assume that the other_connections
     * settings are unchanged.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.OtherConnectionSettings> other_connections = 6;</code>
     */
    private $other_connections;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *           Hash of all settings, including settings that may be omitted from this message
     *           because they are unchanged.
     *     @type \Opamp\Proto\OpAMPConnectionSettings $opamp
     *           Settings to connect to the OpAMP Server.
     *           If this field is not set then the Agent should assume that the settings are
     *           unchanged and should continue using existing settings.
     *           The Agent MUST verify the offered connection settings by actually connecting
     *           before accepting the setting to ensure it does not loose access to the OpAMP
     *           Server due to invalid settings.
     *     @type \Opamp\Proto\TelemetryConnectionSettings $own_metrics
     *           Settings to connect to an OTLP metrics backend to send Agent's own metrics to.
     *           If this field is not set then the Agent should assume that the settings
     *           are unchanged.
     *           Once accepted the Agent should periodically send to the specified destination
     *           its own metrics, i.e. metrics of the Agent process and any custom metrics that
     *           describe the Agent state.
     *           All attributes specified in the identifying_attributes field in AgentDescription
     *           message SHOULD be also specified in the Resource of the reported OTLP metrics.
     *           Attributes specified in the non_identifying_attributes field in
     *           AgentDescription message may be also specified in the Resource of the reported
     *           OTLP metrics, in which case they SHOULD have exactly the same values.
     *           Process metrics MUST follow the conventions for processes:
     *           https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md
     *     @type \Opamp\Proto\TelemetryConnectionSettings $own_traces
     *           Similar to own_metrics, but for traces.
     *     @type \Opamp\Proto\TelemetryConnectionSettings $own_logs
     *           Similar to own_metrics, but for logs.
     *     @type array|\Google\Protobuf\Internal\MapField $other_connections
     *           Another set of connection settings, with a string name associated with each.
     *           How the Agent uses these is Agent-specific. Typically the name represents
     *           the name of the destination to connect to (as it is known to the Agent).
     *           If this field is not set then the Agent should assume that the other_connections
     *           settings are unchanged.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Hash of all settings, including settings that may be omitted from this message
     * because they are unchanged.
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Hash of all settings, including settings that may be omitted from this message
     * because they are unchanged.
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Settings to connect to the OpAMP Server.
     * If this field is not set then the Agent should assume that the settings are
     * unchanged and should continue using existing settings.
     * The Agent MUST verify the offered connection settings by actually connecting
     * before accepting the setting to ensure it does not loose access to the OpAMP
     * Server due to invalid settings.
     *
     * Generated from protobuf field <code>.opamp.proto.OpAMPConnectionSettings opamp = 2;</code>
     * @return \Opamp\Proto\OpAMPConnectionSettings|null
     */
    public function getOpamp()
    {
        return $this->opamp;
    }

    public function hasOpamp()
    {
        return isset($this->opamp);
    }

    public function clearOpamp()
    {
        unset($this->opamp);
    }

    /**
     * Settings to connect to the OpAMP Server.
     * If this field is not set then the Agent should assume that the settings are
     * unchanged and should continue using existing settings.
     * The Agent MUST verify the offered connection settings by actually connecting
     * before accepting the setting to ensure it does not loose access to the OpAMP
     * Server due to invalid settings.
     *
     * Generated from protobuf field <code>.opamp.proto.OpAMPConnectionSettings opamp = 2;</code>
     * @param \Opamp\Proto\OpAMPConnectionSettings $var
     * @return $this
     */
    public function setOpamp($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\OpAMPConnectionSettings::class);
        $this->opamp = $var;

        return $this;
    }

    /**
     * Settings to connect to an OTLP metrics backend to send Agent's own metrics to.
     * If this field is not set then the Agent should assume that the settings
     * are unchanged.
     * Once accepted the Agent should periodically send to the specified destination
     * its own metrics, i.e. metrics of the Agent process and any custom metrics that
     * describe the Agent state.
     * All attributes specified in the identifying_attributes field in AgentDescription
     * message SHOULD be also specified in the Resource of the reported OTLP metrics.
     * Attributes specified in the non_identifying_attributes field in
     * AgentDescription message may be also specified in the Resource of the reported
     * OTLP metrics, in which case they SHOULD have exactly the same values.
     * Process metrics MUST follow the conventions for processes:
     * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_metrics = 3;</code>
     * @return \Opamp\Proto\TelemetryConnectionSettings|null
     */
    public function getOwnMetrics()
    {
        return $this->own_metrics;
    }

    public function hasOwnMetrics()
    {
        return isset($this->own_metrics);
    }

    public function clearOwnMetrics()
    {
        unset($this->own_metrics);
    }

    /**
     * Settings to connect to an OTLP metrics backend to send Agent's own metrics to.
     * If this field is not set then the Agent should assume that the settings
     * are unchanged.
     * Once accepted the Agent should periodically send to the specified destination
     * its own metrics, i.e. metrics of the Agent process and any custom metrics that
     * describe the Agent state.
     * All attributes specified in the identifying_attributes field in AgentDescription
     * message SHOULD be also specified in the Resource of the reported OTLP metrics.
     * Attributes specified in the non_identifying_attributes field in
     * AgentDescription message may be also specified in the Resource of the reported
     * OTLP metrics, in which case they SHOULD have exactly the same values.
     * Process metrics MUST follow the conventions for processes:
     * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_metrics = 3;</code>
     * @param \Opamp\Proto\TelemetryConnectionSettings $var
     * @return $this
     */
    public function setOwnMetrics($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\TelemetryConnectionSettings::class);
        $this->own_metrics = $var;

        return $this;
    }

    /**
     * Similar to own_metrics, but for traces.
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_traces = 4;</code>
     * @return \Opamp\Proto\TelemetryConnectionSettings|null
     */
    public function getOwnTraces()
    {
        return $this->own_traces;
    }

    public function hasOwnTraces()
    {
        return isset($this->own_traces);
    }

    public function clearOwnTraces()
    {
        unset($this->own_traces);
    }

    /**
     * Similar to own_metrics, but for traces.
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_traces = 4;</code>
     * @param \Opamp\Proto\TelemetryConnectionSettings $var
     * @return $this
     */
    public function setOwnTraces($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\TelemetryConnectionSettings::class);
        $this->own_traces = $var;

        return $this;
    }

    /**
     * Similar to own_metrics, but for logs.
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_logs = 5;</code>
     * @return \Opamp\Proto\TelemetryConnectionSettings|null
     */
    public function getOwnLogs()
    {
        return $this->own_logs;
    }

    public function hasOwnLogs()
    {
        return isset($this->own_logs);
    }

    public function clearOwnLogs()
    {
        unset($this->own_logs);
    }

    /**
     * Similar to own_metrics, but for logs.
     *
     * Generated from protobuf field <code>.opamp.proto.TelemetryConnectionSettings own_logs = 5;</code>
     * @param \Opamp\Proto\TelemetryConnectionSettings $var
     * @return $this
     */
    public function setOwnLogs($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\TelemetryConnectionSettings::class);
        $this->own_logs = $var;

        return $this;
    }

    /**
     * Another set of connection settings, with a string name associated with each.
     * How the Agent uses these is Agent-specific. Typically the name represents
     * the name of the destination to connect to (as it is known to the Agent).
     * If this field is not set then the Agent should assume that the other_connections
     * settings are unchanged.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.OtherConnectionSettings> other_connections = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOtherConnections()
    {
        return $this->other_connections;
    }

    /**
     * Another set of connection settings, with a string name associated with each.
     * How the Agent uses these is Agent-specific. Typically the name represents
     * the name of the destination to connect to (as it is known to the Agent).
     * If this field is not set then the Agent should assume that the other_connections
     * settings are unchanged.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.OtherConnectionSettings> other_connections = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOtherConnections($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opamp\Proto\OtherConnectionSettings::class);
        $this->other_connections = $arr;

        return $this;
    }

}

