<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.CustomMessage</code>
 */
class CustomMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * A reverse FQDN that uniquely identifies the capability and matches one of the
     * capabilities in the CustomCapabilities message.
     * Status: [Development]
     *
     * Generated from protobuf field <code>string capability = 1;</code>
     */
    protected $capability = '';
    /**
     * Type of message within the capability. The capability defines the types of custom
     * messages that are used to implement the capability. The type must only be unique
     * within the capability.
     * Status: [Development]
     *
     * Generated from protobuf field <code>string type = 2;</code>
     */
    protected $type = '';
    /**
     * Binary data of the message. The capability must specify the format of the contents
     * of the data for each custom message type it defines.
     * Status: [Development]
     *
     * Generated from protobuf field <code>bytes data = 3;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $capability
     *           A reverse FQDN that uniquely identifies the capability and matches one of the
     *           capabilities in the CustomCapabilities message.
     *           Status: [Development]
     *     @type string $type
     *           Type of message within the capability. The capability defines the types of custom
     *           messages that are used to implement the capability. The type must only be unique
     *           within the capability.
     *           Status: [Development]
     *     @type string $data
     *           Binary data of the message. The capability must specify the format of the contents
     *           of the data for each custom message type it defines.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * A reverse FQDN that uniquely identifies the capability and matches one of the
     * capabilities in the CustomCapabilities message.
     * Status: [Development]
     *
     * Generated from protobuf field <code>string capability = 1;</code>
     * @return string
     */
    public function getCapability()
    {
        return $this->capability;
    }

    /**
     * A reverse FQDN that uniquely identifies the capability and matches one of the
     * capabilities in the CustomCapabilities message.
     * Status: [Development]
     *
     * Generated from protobuf field <code>string capability = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCapability($var)
    {
        GPBUtil::checkString($var, True);
        $this->capability = $var;

        return $this;
    }

    /**
     * Type of message within the capability. The capability defines the types of custom
     * messages that are used to implement the capability. The type must only be unique
     * within the capability.
     * Status: [Development]
     *
     * Generated from protobuf field <code>string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Type of message within the capability. The capability defines the types of custom
     * messages that are used to implement the capability. The type must only be unique
     * within the capability.
     * Status: [Development]
     *
     * Generated from protobuf field <code>string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Binary data of the message. The capability must specify the format of the contents
     * of the data for each custom message type it defines.
     * Status: [Development]
     *
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Binary data of the message. The capability must specify the format of the contents
     * of the data for each custom message type it defines.
     * Status: [Development]
     *
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

