<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The OpAMPConnectionSettings message is a collection of fields which comprise an
 * offer from the Server to the Agent to use the specified settings for OpAMP
 * connection.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.OpAMPConnectionSettings</code>
 */
class OpAMPConnectionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * OpAMP Server URL This MUST be a WebSocket or HTTP URL and MUST be non-empty, for
     * example: "wss://example.com:4318/v1/opamp"
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     */
    protected $destination_endpoint = '';
    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     */
    protected $headers = null;
    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     */
    protected $certificate = null;
    /**
     * The Agent MUST periodically send an AgentToServer message if the
     * AgentCapabilities_ReportsHeartbeat capability is true. At a minimum the instance_uid
     * field MUST be set.
     * An HTTP Client MUST use the value as polling interval, if heartbeat_interval_seconds is non-zero.
     * A heartbeat is used to keep the connection active and inform the server that the Agent
     * is still alive and active.
     * If this field has no value or is set to 0, the Agent should not send any heartbeats.
     * Status: [Development]
     *
     * Generated from protobuf field <code>uint64 heartbeat_interval_seconds = 4;</code>
     */
    protected $heartbeat_interval_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $destination_endpoint
     *           OpAMP Server URL This MUST be a WebSocket or HTTP URL and MUST be non-empty, for
     *           example: "wss://example.com:4318/v1/opamp"
     *     @type \Opamp\Proto\Headers $headers
     *           Optional headers to use when connecting. Typically used to set access tokens or
     *           other authorization headers. For HTTP-based protocols the Agent should
     *           set these in the request headers.
     *           For example:
     *           key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *     @type \Opamp\Proto\TLSCertificate $certificate
     *           The Agent should use the offered certificate to connect to the destination
     *           from now on. If the Agent is able to validate and connect using the offered
     *           certificate the Agent SHOULD forget any previous client certificates
     *           for this connection.
     *           This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     *           This field can be used to perform a client certificate revocation/rotation.
     *     @type int|string $heartbeat_interval_seconds
     *           The Agent MUST periodically send an AgentToServer message if the
     *           AgentCapabilities_ReportsHeartbeat capability is true. At a minimum the instance_uid
     *           field MUST be set.
     *           An HTTP Client MUST use the value as polling interval, if heartbeat_interval_seconds is non-zero.
     *           A heartbeat is used to keep the connection active and inform the server that the Agent
     *           is still alive and active.
     *           If this field has no value or is set to 0, the Agent should not send any heartbeats.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * OpAMP Server URL This MUST be a WebSocket or HTTP URL and MUST be non-empty, for
     * example: "wss://example.com:4318/v1/opamp"
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     * @return string
     */
    public function getDestinationEndpoint()
    {
        return $this->destination_endpoint;
    }

    /**
     * OpAMP Server URL This MUST be a WebSocket or HTTP URL and MUST be non-empty, for
     * example: "wss://example.com:4318/v1/opamp"
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDestinationEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination_endpoint = $var;

        return $this;
    }

    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     * @return \Opamp\Proto\Headers|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     * @param \Opamp\Proto\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\Headers::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     * @return \Opamp\Proto\TLSCertificate|null
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    public function hasCertificate()
    {
        return isset($this->certificate);
    }

    public function clearCertificate()
    {
        unset($this->certificate);
    }

    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     * @param \Opamp\Proto\TLSCertificate $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\TLSCertificate::class);
        $this->certificate = $var;

        return $this;
    }

    /**
     * The Agent MUST periodically send an AgentToServer message if the
     * AgentCapabilities_ReportsHeartbeat capability is true. At a minimum the instance_uid
     * field MUST be set.
     * An HTTP Client MUST use the value as polling interval, if heartbeat_interval_seconds is non-zero.
     * A heartbeat is used to keep the connection active and inform the server that the Agent
     * is still alive and active.
     * If this field has no value or is set to 0, the Agent should not send any heartbeats.
     * Status: [Development]
     *
     * Generated from protobuf field <code>uint64 heartbeat_interval_seconds = 4;</code>
     * @return int|string
     */
    public function getHeartbeatIntervalSeconds()
    {
        return $this->heartbeat_interval_seconds;
    }

    /**
     * The Agent MUST periodically send an AgentToServer message if the
     * AgentCapabilities_ReportsHeartbeat capability is true. At a minimum the instance_uid
     * field MUST be set.
     * An HTTP Client MUST use the value as polling interval, if heartbeat_interval_seconds is non-zero.
     * A heartbeat is used to keep the connection active and inform the server that the Agent
     * is still alive and active.
     * If this field has no value or is set to 0, the Agent should not send any heartbeats.
     * Status: [Development]
     *
     * Generated from protobuf field <code>uint64 heartbeat_interval_seconds = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeartbeatIntervalSeconds($var)
    {
        GPBUtil::checkUint64($var);
        $this->heartbeat_interval_seconds = $var;

        return $this;
    }

}

