<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * List of packages that the Server offers to the Agent.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.PackagesAvailable</code>
 */
class PackagesAvailable extends \Google\Protobuf\Internal\Message
{
    /**
     * Map of packages. Keys are package names, values are the packages available for download.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.PackageAvailable> packages = 1;</code>
     */
    private $packages;
    /**
     * Aggregate hash of all remotely installed packages. The Agent SHOULD include this
     * value in subsequent PackageStatuses messages. This in turn allows the management
     * Server to identify that a different set of packages is available for the Agent
     * and specify the available packages in the next ServerToAgent message.
     * This field MUST be always set if the management Server supports packages
     * of agents.
     * The hash is calculated as an aggregate of all packages names and content.
     *
     * Generated from protobuf field <code>bytes all_packages_hash = 2;</code>
     */
    protected $all_packages_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $packages
     *           Map of packages. Keys are package names, values are the packages available for download.
     *     @type string $all_packages_hash
     *           Aggregate hash of all remotely installed packages. The Agent SHOULD include this
     *           value in subsequent PackageStatuses messages. This in turn allows the management
     *           Server to identify that a different set of packages is available for the Agent
     *           and specify the available packages in the next ServerToAgent message.
     *           This field MUST be always set if the management Server supports packages
     *           of agents.
     *           The hash is calculated as an aggregate of all packages names and content.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Map of packages. Keys are package names, values are the packages available for download.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.PackageAvailable> packages = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * Map of packages. Keys are package names, values are the packages available for download.
     *
     * Generated from protobuf field <code>map<string, .opamp.proto.PackageAvailable> packages = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPackages($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opamp\Proto\PackageAvailable::class);
        $this->packages = $arr;

        return $this;
    }

    /**
     * Aggregate hash of all remotely installed packages. The Agent SHOULD include this
     * value in subsequent PackageStatuses messages. This in turn allows the management
     * Server to identify that a different set of packages is available for the Agent
     * and specify the available packages in the next ServerToAgent message.
     * This field MUST be always set if the management Server supports packages
     * of agents.
     * The hash is calculated as an aggregate of all packages names and content.
     *
     * Generated from protobuf field <code>bytes all_packages_hash = 2;</code>
     * @return string
     */
    public function getAllPackagesHash()
    {
        return $this->all_packages_hash;
    }

    /**
     * Aggregate hash of all remotely installed packages. The Agent SHOULD include this
     * value in subsequent PackageStatuses messages. This in turn allows the management
     * Server to identify that a different set of packages is available for the Agent
     * and specify the available packages in the next ServerToAgent message.
     * This field MUST be always set if the management Server supports packages
     * of agents.
     * The hash is calculated as an aggregate of all packages names and content.
     *
     * Generated from protobuf field <code>bytes all_packages_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAllPackagesHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->all_packages_hash = $var;

        return $this;
    }

}

