<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The status of a single package.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.PackageStatus</code>
 */
class PackageStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Package name. MUST be always set and MUST match the key in the packages field
     * of PackageStatuses message.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The version of the package that the Agent has.
     * MUST be set if the Agent has this package.
     * MUST be empty if the Agent does not have this package. This may be the case
     * for example if the package was offered by the Server but failed to install
     * and the Agent did not have this package previously.
     *
     * Generated from protobuf field <code>string agent_has_version = 2;</code>
     */
    protected $agent_has_version = '';
    /**
     * The hash of the package that the Agent has.
     * MUST be set if the Agent has this package.
     * MUST be empty if the Agent does not have this package. This may be the case for
     * example if the package was offered by the Server but failed to install and the
     * Agent did not have this package previously.
     *
     * Generated from protobuf field <code>bytes agent_has_hash = 3;</code>
     */
    protected $agent_has_hash = '';
    /**
     * The version of the package that the Server offered to the Agent.
     * MUST be set if the installation of the package is initiated by an earlier offer
     * from the Server to install this package.
     * MUST be empty if the Agent has this package but it was installed locally and
     * was not offered by the Server.
     * Note that it is possible for both agent_has_version and server_offered_version
     * fields to be set and to have different values. This is for example possible if
     * the Agent already has a version of the package successfully installed, the Server
     * offers a different version, but the Agent fails to install that version.
     *
     * Generated from protobuf field <code>string server_offered_version = 4;</code>
     */
    protected $server_offered_version = '';
    /**
     * The hash of the package that the Server offered to the Agent.
     * MUST be set if the installation of the package is initiated by an earlier
     * offer from the Server to install this package.
     * MUST be empty if the Agent has this package but it was installed locally and
     * was not offered by the Server.
     * Note that it is possible for both agent_has_hash and server_offered_hash
     * fields to be set and to have different values. This is for example possible if
     * the Agent already has a version of the package successfully installed, the
     * Server offers a different version, but the Agent fails to install that version.
     *
     * Generated from protobuf field <code>bytes server_offered_hash = 5;</code>
     */
    protected $server_offered_hash = '';
    /**
     * Generated from protobuf field <code>.opamp.proto.PackageStatusEnum status = 6;</code>
     */
    protected $status = 0;
    /**
     * Error message if the status is erroneous.
     *
     * Generated from protobuf field <code>string error_message = 7;</code>
     */
    protected $error_message = '';
    /**
     * Optional details that may be of interest to a user.
     * Should only be set if status is Downloading.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.PackageDownloadDetails download_details = 8;</code>
     */
    protected $download_details = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Package name. MUST be always set and MUST match the key in the packages field
     *           of PackageStatuses message.
     *     @type string $agent_has_version
     *           The version of the package that the Agent has.
     *           MUST be set if the Agent has this package.
     *           MUST be empty if the Agent does not have this package. This may be the case
     *           for example if the package was offered by the Server but failed to install
     *           and the Agent did not have this package previously.
     *     @type string $agent_has_hash
     *           The hash of the package that the Agent has.
     *           MUST be set if the Agent has this package.
     *           MUST be empty if the Agent does not have this package. This may be the case for
     *           example if the package was offered by the Server but failed to install and the
     *           Agent did not have this package previously.
     *     @type string $server_offered_version
     *           The version of the package that the Server offered to the Agent.
     *           MUST be set if the installation of the package is initiated by an earlier offer
     *           from the Server to install this package.
     *           MUST be empty if the Agent has this package but it was installed locally and
     *           was not offered by the Server.
     *           Note that it is possible for both agent_has_version and server_offered_version
     *           fields to be set and to have different values. This is for example possible if
     *           the Agent already has a version of the package successfully installed, the Server
     *           offers a different version, but the Agent fails to install that version.
     *     @type string $server_offered_hash
     *           The hash of the package that the Server offered to the Agent.
     *           MUST be set if the installation of the package is initiated by an earlier
     *           offer from the Server to install this package.
     *           MUST be empty if the Agent has this package but it was installed locally and
     *           was not offered by the Server.
     *           Note that it is possible for both agent_has_hash and server_offered_hash
     *           fields to be set and to have different values. This is for example possible if
     *           the Agent already has a version of the package successfully installed, the
     *           Server offers a different version, but the Agent fails to install that version.
     *     @type int $status
     *     @type string $error_message
     *           Error message if the status is erroneous.
     *     @type \Opamp\Proto\PackageDownloadDetails $download_details
     *           Optional details that may be of interest to a user.
     *           Should only be set if status is Downloading.
     *           Status: [Development]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Package name. MUST be always set and MUST match the key in the packages field
     * of PackageStatuses message.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Package name. MUST be always set and MUST match the key in the packages field
     * of PackageStatuses message.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The version of the package that the Agent has.
     * MUST be set if the Agent has this package.
     * MUST be empty if the Agent does not have this package. This may be the case
     * for example if the package was offered by the Server but failed to install
     * and the Agent did not have this package previously.
     *
     * Generated from protobuf field <code>string agent_has_version = 2;</code>
     * @return string
     */
    public function getAgentHasVersion()
    {
        return $this->agent_has_version;
    }

    /**
     * The version of the package that the Agent has.
     * MUST be set if the Agent has this package.
     * MUST be empty if the Agent does not have this package. This may be the case
     * for example if the package was offered by the Server but failed to install
     * and the Agent did not have this package previously.
     *
     * Generated from protobuf field <code>string agent_has_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAgentHasVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->agent_has_version = $var;

        return $this;
    }

    /**
     * The hash of the package that the Agent has.
     * MUST be set if the Agent has this package.
     * MUST be empty if the Agent does not have this package. This may be the case for
     * example if the package was offered by the Server but failed to install and the
     * Agent did not have this package previously.
     *
     * Generated from protobuf field <code>bytes agent_has_hash = 3;</code>
     * @return string
     */
    public function getAgentHasHash()
    {
        return $this->agent_has_hash;
    }

    /**
     * The hash of the package that the Agent has.
     * MUST be set if the Agent has this package.
     * MUST be empty if the Agent does not have this package. This may be the case for
     * example if the package was offered by the Server but failed to install and the
     * Agent did not have this package previously.
     *
     * Generated from protobuf field <code>bytes agent_has_hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAgentHasHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->agent_has_hash = $var;

        return $this;
    }

    /**
     * The version of the package that the Server offered to the Agent.
     * MUST be set if the installation of the package is initiated by an earlier offer
     * from the Server to install this package.
     * MUST be empty if the Agent has this package but it was installed locally and
     * was not offered by the Server.
     * Note that it is possible for both agent_has_version and server_offered_version
     * fields to be set and to have different values. This is for example possible if
     * the Agent already has a version of the package successfully installed, the Server
     * offers a different version, but the Agent fails to install that version.
     *
     * Generated from protobuf field <code>string server_offered_version = 4;</code>
     * @return string
     */
    public function getServerOfferedVersion()
    {
        return $this->server_offered_version;
    }

    /**
     * The version of the package that the Server offered to the Agent.
     * MUST be set if the installation of the package is initiated by an earlier offer
     * from the Server to install this package.
     * MUST be empty if the Agent has this package but it was installed locally and
     * was not offered by the Server.
     * Note that it is possible for both agent_has_version and server_offered_version
     * fields to be set and to have different values. This is for example possible if
     * the Agent already has a version of the package successfully installed, the Server
     * offers a different version, but the Agent fails to install that version.
     *
     * Generated from protobuf field <code>string server_offered_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setServerOfferedVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_offered_version = $var;

        return $this;
    }

    /**
     * The hash of the package that the Server offered to the Agent.
     * MUST be set if the installation of the package is initiated by an earlier
     * offer from the Server to install this package.
     * MUST be empty if the Agent has this package but it was installed locally and
     * was not offered by the Server.
     * Note that it is possible for both agent_has_hash and server_offered_hash
     * fields to be set and to have different values. This is for example possible if
     * the Agent already has a version of the package successfully installed, the
     * Server offers a different version, but the Agent fails to install that version.
     *
     * Generated from protobuf field <code>bytes server_offered_hash = 5;</code>
     * @return string
     */
    public function getServerOfferedHash()
    {
        return $this->server_offered_hash;
    }

    /**
     * The hash of the package that the Server offered to the Agent.
     * MUST be set if the installation of the package is initiated by an earlier
     * offer from the Server to install this package.
     * MUST be empty if the Agent has this package but it was installed locally and
     * was not offered by the Server.
     * Note that it is possible for both agent_has_hash and server_offered_hash
     * fields to be set and to have different values. This is for example possible if
     * the Agent already has a version of the package successfully installed, the
     * Server offers a different version, but the Agent fails to install that version.
     *
     * Generated from protobuf field <code>bytes server_offered_hash = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServerOfferedHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->server_offered_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.PackageStatusEnum status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.PackageStatusEnum status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Opamp\Proto\PackageStatusEnum::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Error message if the status is erroneous.
     *
     * Generated from protobuf field <code>string error_message = 7;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Error message if the status is erroneous.
     *
     * Generated from protobuf field <code>string error_message = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Optional details that may be of interest to a user.
     * Should only be set if status is Downloading.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.PackageDownloadDetails download_details = 8;</code>
     * @return \Opamp\Proto\PackageDownloadDetails|null
     */
    public function getDownloadDetails()
    {
        return $this->download_details;
    }

    public function hasDownloadDetails()
    {
        return isset($this->download_details);
    }

    public function clearDownloadDetails()
    {
        unset($this->download_details);
    }

    /**
     * Optional details that may be of interest to a user.
     * Should only be set if status is Downloading.
     * Status: [Development]
     *
     * Generated from protobuf field <code>.opamp.proto.PackageDownloadDetails download_details = 8;</code>
     * @param \Opamp\Proto\PackageDownloadDetails $var
     * @return $this
     */
    public function setDownloadDetails($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\PackageDownloadDetails::class);
        $this->download_details = $var;

        return $this;
    }

}

