<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use UnexpectedValueException;

/**
 * The type of the package, either an addon or a top-level package.
 * Status: [Beta]
 *
 * Protobuf type <code>opamp.proto.PackageType</code>
 */
class PackageType
{
    /**
     * Generated from protobuf enum <code>PackageType_TopLevel = 0;</code>
     */
    const PackageType_TopLevel = 0;
    /**
     * Generated from protobuf enum <code>PackageType_Addon = 1;</code>
     */
    const PackageType_Addon = 1;

    private static $valueToName = [
        self::PackageType_TopLevel => 'PackageType_TopLevel',
        self::PackageType_Addon => 'PackageType_Addon',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

