<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Additional details that an agent can use to describe an in-progress package download.
 * Status: [Development]
 *
 * Generated from protobuf message <code>opamp.proto.PackageDownloadDetails</code>
 */
class PackageDownloadDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * The package download progress as a percentage.
     *
     * Generated from protobuf field <code>double download_percent = 1;</code>
     */
    protected $download_percent = 0.0;
    /**
     * The current package download rate in bytes per second.
     *
     * Generated from protobuf field <code>double download_bytes_per_second = 2;</code>
     */
    protected $download_bytes_per_second = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $download_percent
     *           The package download progress as a percentage.
     *     @type float $download_bytes_per_second
     *           The current package download rate in bytes per second.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * The package download progress as a percentage.
     *
     * Generated from protobuf field <code>double download_percent = 1;</code>
     * @return float
     */
    public function getDownloadPercent()
    {
        return $this->download_percent;
    }

    /**
     * The package download progress as a percentage.
     *
     * Generated from protobuf field <code>double download_percent = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDownloadPercent($var)
    {
        GPBUtil::checkDouble($var);
        $this->download_percent = $var;

        return $this;
    }

    /**
     * The current package download rate in bytes per second.
     *
     * Generated from protobuf field <code>double download_bytes_per_second = 2;</code>
     * @return float
     */
    public function getDownloadBytesPerSecond()
    {
        return $this->download_bytes_per_second;
    }

    /**
     * The current package download rate in bytes per second.
     *
     * Generated from protobuf field <code>double download_bytes_per_second = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setDownloadBytesPerSecond($var)
    {
        GPBUtil::checkDouble($var);
        $this->download_bytes_per_second = $var;

        return $this;
    }

}

