<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>opamp.proto.RemoteConfigStatuses</code>
 */
class RemoteConfigStatuses
{
    /**
     * The value of status field is not set.
     *
     * Generated from protobuf enum <code>RemoteConfigStatuses_UNSET = 0;</code>
     */
    const RemoteConfigStatuses_UNSET = 0;
    /**
     * Remote config was successfully applied by the Agent.
     *
     * Generated from protobuf enum <code>RemoteConfigStatuses_APPLIED = 1;</code>
     */
    const RemoteConfigStatuses_APPLIED = 1;
    /**
     * Agent is currently applying the remote config that it received earlier.
     *
     * Generated from protobuf enum <code>RemoteConfigStatuses_APPLYING = 2;</code>
     */
    const RemoteConfigStatuses_APPLYING = 2;
    /**
     * Agent tried to apply the config received earlier, but it failed.
     * See error_message for more details.
     *
     * Generated from protobuf enum <code>RemoteConfigStatuses_FAILED = 3;</code>
     */
    const RemoteConfigStatuses_FAILED = 3;

    private static $valueToName = [
        self::RemoteConfigStatuses_UNSET => 'RemoteConfigStatuses_UNSET',
        self::RemoteConfigStatuses_APPLIED => 'RemoteConfigStatuses_APPLIED',
        self::RemoteConfigStatuses_APPLYING => 'RemoteConfigStatuses_APPLYING',
        self::RemoteConfigStatuses_FAILED => 'RemoteConfigStatuses_FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

