<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opamp.proto.RemoteConfigStatus</code>
 */
class RemoteConfigStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * The hash of the remote config that was last received by this Agent in the
     * AgentRemoteConfig.config_hash field.
     * The Server SHOULD compare this hash with the config hash
     * it has for the Agent and if the hashes are different the Server MUST include
     * the remote_config field in the response in the ServerToAgent message.
     *
     * Generated from protobuf field <code>bytes last_remote_config_hash = 1;</code>
     */
    protected $last_remote_config_hash = '';
    /**
     * Generated from protobuf field <code>.opamp.proto.RemoteConfigStatuses status = 2;</code>
     */
    protected $status = 0;
    /**
     * Optional error message if status==FAILED.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $last_remote_config_hash
     *           The hash of the remote config that was last received by this Agent in the
     *           AgentRemoteConfig.config_hash field.
     *           The Server SHOULD compare this hash with the config hash
     *           it has for the Agent and if the hashes are different the Server MUST include
     *           the remote_config field in the response in the ServerToAgent message.
     *     @type int $status
     *     @type string $error_message
     *           Optional error message if status==FAILED.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * The hash of the remote config that was last received by this Agent in the
     * AgentRemoteConfig.config_hash field.
     * The Server SHOULD compare this hash with the config hash
     * it has for the Agent and if the hashes are different the Server MUST include
     * the remote_config field in the response in the ServerToAgent message.
     *
     * Generated from protobuf field <code>bytes last_remote_config_hash = 1;</code>
     * @return string
     */
    public function getLastRemoteConfigHash()
    {
        return $this->last_remote_config_hash;
    }

    /**
     * The hash of the remote config that was last received by this Agent in the
     * AgentRemoteConfig.config_hash field.
     * The Server SHOULD compare this hash with the config hash
     * it has for the Agent and if the hashes are different the Server MUST include
     * the remote_config field in the response in the ServerToAgent message.
     *
     * Generated from protobuf field <code>bytes last_remote_config_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLastRemoteConfigHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->last_remote_config_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.RemoteConfigStatuses status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.RemoteConfigStatuses status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Opamp\Proto\RemoteConfigStatuses::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Optional error message if status==FAILED.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Optional error message if status==FAILED.
     *
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

