<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>opamp.proto.ServerErrorResponseType</code>
 */
class ServerErrorResponseType
{
    /**
     * Unknown error. Something went wrong, but it is not known what exactly.
     * The Agent SHOULD NOT retry the message.
     * The error_message field may contain a description of the problem.
     *
     * Generated from protobuf enum <code>ServerErrorResponseType_Unknown = 0;</code>
     */
    const ServerErrorResponseType_Unknown = 0;
    /**
     * The AgentToServer message was malformed. The Agent SHOULD NOT retry
     * the message.
     *
     * Generated from protobuf enum <code>ServerErrorResponseType_BadRequest = 1;</code>
     */
    const ServerErrorResponseType_BadRequest = 1;
    /**
     * The Server is overloaded and unable to process the request. The Agent
     * should retry the message later. retry_info field may be optionally
     * set with additional information about retrying.
     *
     * Generated from protobuf enum <code>ServerErrorResponseType_Unavailable = 2;</code>
     */
    const ServerErrorResponseType_Unavailable = 2;

    private static $valueToName = [
        self::ServerErrorResponseType_Unknown => 'ServerErrorResponseType_Unknown',
        self::ServerErrorResponseType_BadRequest => 'ServerErrorResponseType_BadRequest',
        self::ServerErrorResponseType_Unavailable => 'ServerErrorResponseType_Unavailable',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

