<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ServerToAgentCommand is sent from the Server to the Agent to request that the Agent
 * perform a command.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.ServerToAgentCommand</code>
 */
class ServerToAgentCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.opamp.proto.CommandType type = 1;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.CommandType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.opamp.proto.CommandType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Opamp\Proto\CommandType::class);
        $this->type = $var;

        return $this;
    }

}

