<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opamp.proto

namespace Opamp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The TelemetryConnectionSettings message is a collection of fields which comprise an
 * offer from the Server to the Agent to use the specified settings for a network
 * connection to report own telemetry.
 * Status: [Beta]
 *
 * Generated from protobuf message <code>opamp.proto.TelemetryConnectionSettings</code>
 */
class TelemetryConnectionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * The value MUST be a full URL an OTLP/HTTP/Protobuf receiver with path. Schema
     * SHOULD begin with "https://", for example "https://example.com:4318/v1/metrics"
     * The Agent MAY refuse to send the telemetry if the URL begins with "http://".
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     */
    protected $destination_endpoint = '';
    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     */
    protected $headers = null;
    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     */
    protected $certificate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $destination_endpoint
     *           The value MUST be a full URL an OTLP/HTTP/Protobuf receiver with path. Schema
     *           SHOULD begin with "https://", for example "https://example.com:4318/v1/metrics"
     *           The Agent MAY refuse to send the telemetry if the URL begins with "http://".
     *     @type \Opamp\Proto\Headers $headers
     *           Optional headers to use when connecting. Typically used to set access tokens or
     *           other authorization headers. For HTTP-based protocols the Agent should
     *           set these in the request headers.
     *           For example:
     *           key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *     @type \Opamp\Proto\TLSCertificate $certificate
     *           The Agent should use the offered certificate to connect to the destination
     *           from now on. If the Agent is able to validate and connect using the offered
     *           certificate the Agent SHOULD forget any previous client certificates
     *           for this connection.
     *           This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     *           This field can be used to perform a client certificate revocation/rotation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opamp::initOnce();
        parent::__construct($data);
    }

    /**
     * The value MUST be a full URL an OTLP/HTTP/Protobuf receiver with path. Schema
     * SHOULD begin with "https://", for example "https://example.com:4318/v1/metrics"
     * The Agent MAY refuse to send the telemetry if the URL begins with "http://".
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     * @return string
     */
    public function getDestinationEndpoint()
    {
        return $this->destination_endpoint;
    }

    /**
     * The value MUST be a full URL an OTLP/HTTP/Protobuf receiver with path. Schema
     * SHOULD begin with "https://", for example "https://example.com:4318/v1/metrics"
     * The Agent MAY refuse to send the telemetry if the URL begins with "http://".
     *
     * Generated from protobuf field <code>string destination_endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDestinationEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination_endpoint = $var;

        return $this;
    }

    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     * @return \Opamp\Proto\Headers|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Optional headers to use when connecting. Typically used to set access tokens or
     * other authorization headers. For HTTP-based protocols the Agent should
     * set these in the request headers.
     * For example:
     * key="Authorization", Value="Basic YWxhZGRpbjpvcGVuc2VzYW1l".
     *
     * Generated from protobuf field <code>.opamp.proto.Headers headers = 2;</code>
     * @param \Opamp\Proto\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\Headers::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     * @return \Opamp\Proto\TLSCertificate|null
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    public function hasCertificate()
    {
        return isset($this->certificate);
    }

    public function clearCertificate()
    {
        unset($this->certificate);
    }

    /**
     * The Agent should use the offered certificate to connect to the destination
     * from now on. If the Agent is able to validate and connect using the offered
     * certificate the Agent SHOULD forget any previous client certificates
     * for this connection.
     * This field is optional: if omitted the client SHOULD NOT use a client-side certificate.
     * This field can be used to perform a client certificate revocation/rotation.
     *
     * Generated from protobuf field <code>.opamp.proto.TLSCertificate certificate = 3;</code>
     * @param \Opamp\Proto\TLSCertificate $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkMessage($var, \Opamp\Proto\TLSCertificate::class);
        $this->certificate = $var;

        return $this;
    }

}

