/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * DO NOT EDIT, this is an Auto-generated file from:
 * buildscripts/semantic-convention/templates/registry/semantic_attributes-h.j2
 */












#pragma once


namespace opentelemetry {
namespace semconv
{
namespace az
{

/**
 * <a href="https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers">Azure Resource Provider Namespace</a> as recognized by the client.
 */
static constexpr const char *kAzNamespace
 = "az.namespace";

/**
 * The unique identifier of the service request. It's generated by the Azure service and returned with the response.
 */
static constexpr const char *kAzServiceRequestId
 = "az.service_request_id";



}
}
}
