---

name: build-php-code-for-packages

on:
  workflow_call: ~
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  build-php-code-for-packages:
    name: build-php-code-for-packages
    runs-on: ubuntu-latest
    timeout-minutes: 300
    strategy:
      fail-fast: false
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build PHP code (production code and its dependencies) for the packages
        run: |
          source ./upstream/tools/read_properties.sh
          read_properties upstream/project.properties PROJECT_PROPERTIES
          PHP_VERSIONS=${PROJECT_PROPERTIES_SUPPORTED_PHP_VERSIONS//[()]/}
          ./tools/build/build_php_code_for_packages.sh --php_versions "${PHP_VERSIONS}"
      - uses: actions/upload-artifact@v7
        with:
          name: php-code-for-packages
          path: |
            _BUILT/php_code_for_packages
            upstream/_BUILT/php_code_for_packages
            _BUILT/NOTICE
