---

name: build-arch-matrix-generator

on:
  workflow_call:
    inputs:
      build_arch:
        required: true
        type: string
        default: 'x86_64'
    outputs:
      matrix-combinations:
        description: "Matrix of architectures to build for"
        value: ${{ jobs.setup-build-matrix.outputs.matrix-combinations }}

permissions:
  contents: read

jobs:
  setup-build-matrix:
    name: setup-build-matrix
    runs-on: ubuntu-latest
    env:
      SELECTED_ARCH: ${{ inputs.build_arch }}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}
    steps:
      - name: Create build matrix
        id: setup-matrix-combinations
        run: |
          MATRIX=''
          if [ "${SELECTED_ARCH}" == "x86_64" ] ||  [ "${SELECTED_ARCH}" == "all" ]; then
            echo "${SELECTED_ARCH} selected. Adding x86_64"
            MATRIX+='{"arch": "linux-x86-64", "goarch": "amd64", "packages": "deb rpm"}, {"arch": "linuxmusl-x86-64", "goarch": "amd64", "packages": "apk"},'
          fi
          if [ "${SELECTED_ARCH}" == "arm64" ] ||  [ "${SELECTED_ARCH}" == "all" ]; then
            echo "${SELECTED_ARCH} selected. Adding arm64"
            MATRIX+='{"arch": "linux-arm64", "goarch": "arm64", "packages": "deb rpm"},{"arch": "linuxmusl-arm64", "goarch": "arm64", "packages": "apk"},'
          fi
          echo "matrix-combinations={\"include\":[$MATRIX]}"

          echo "matrix-combinations={\"include\":[$MATRIX]}" >> $GITHUB_OUTPUT