---

# Generates list of supported PHP versions by reading supported_php_versions property in ./elastic-otel-php.properties
name: generate-php-versions

on:
  workflow_call:
    outputs:
      php-versions:
        description: "Generated list of supported PHP versions"
        value: ${{ jobs.generate-php-versions.outputs.php-versions }}

permissions:
  contents: read

jobs:
  generate-php-versions:
    name: generate-php-versions
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{ steps.generate.outputs.php-versions }}
    steps:
      - uses: actions/checkout@v4
      - id: generate
        run: |
          source ./tools/read_properties.sh
          read_properties elastic-otel-php.properties PROJECT_PROPERTIES
          PHP_VERSIONS=${PROJECT_PROPERTIES_SUPPORTED_PHP_VERSIONS//[()]/}
          echo "PHP_VERSIONS: ${PHP_VERSIONS}"
          PHP_VERSIONS_JSON=$(echo -n ${PHP_VERSIONS} | jq --raw-input --slurp --compact-output 'split(" ") | map(select(length > 0)) | map({ "php-version": . } )')
          echo "php-versions={\"include\":${PHP_VERSIONS_JSON}}"
          echo "php-versions={\"include\":${PHP_VERSIONS_JSON}}" >> $GITHUB_OUTPUT
