---

name: test-packages-component-tests

on:
  workflow_call: ~

permissions:
  contents: read

env:
  BUILD_PACKAGES_SUB_DIR: build/packages
  COMPONENT_TESTS_LOGS_SUB_DIR: build/component_tests_logs

jobs:
  generate-component-tests-matrix:
    uses: ./.github/workflows/generate-component-tests-matrix.yml

  run-component-tests-in-docker-for-one-matrix-row:
    name: row
    runs-on: 'ubuntu-latest'
    needs: generate-component-tests-matrix
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-component-tests-matrix.outputs.matrix) }}
    env:
      MATRIX_ROW: ${{ matrix.row }}
    steps:
      - uses: actions/checkout@v5
      - name: Download built packages
        uses: actions/download-artifact@v6
        with:
          pattern: packages-*
          path: ${{ env.BUILD_PACKAGES_SUB_DIR }}

      - name: Run component tests
        continue-on-error: false
        run: |
          mv "${PWD}/${{ env.BUILD_PACKAGES_SUB_DIR }}/"*/* "${PWD}/${{ env.BUILD_PACKAGES_SUB_DIR }}/"
          rm -rf "${PWD}/${{ env.BUILD_PACKAGES_SUB_DIR }}/packages-"*
          ./tools/test/component/test_packages_one_matrix_row_in_docker.sh --matrix_row "${MATRIX_ROW}" --packages_dir "${PWD}/${{ env.BUILD_PACKAGES_SUB_DIR }}" --logs_dir "${PWD}/${{ env.COMPONENT_TESTS_LOGS_SUB_DIR }}"
      - uses: actions/upload-artifact@v5
        if: always()
        continue-on-error: false
        with:
          name: test-packages-component-tests-${{ matrix.row }}
          path: |
            ${{ env.COMPONENT_TESTS_LOGS_SUB_DIR }}/*
