---

name: test-otel-unit

on:
  workflow_call: ~

permissions:
  contents: read

env:
  BUILD_PACKAGES: build/packages

jobs:
  generate-php-versions:
    uses: ./.github/workflows/generate-php-versions.yml

  test-otel-unit:
    name: test-otel-unit
    runs-on: 'ubuntu-latest'
    needs: generate-php-versions
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-php-versions.outputs.php-versions) }}
    env:
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Download package artifacts for Debian AMD64
        uses: actions/download-artifact@v5
        with:
          pattern: packages-linux-x86-64
          path: ${{ env.BUILD_PACKAGES }}

      - name: Run otel instrumentation unit tests
        continue-on-error: true
        run: |
          PACKAGE_FILE=$(find ${{ env.BUILD_PACKAGES }} -name elastic*amd64.deb)
          ./tools/build/test_otel_unit_tests_in_docker.sh --php_versions "${PHP_VERSION}" --results_path "build/otel_unit_results" --deb_package ${PACKAGE_FILE}

      - name: Generate test summary
        if: always()
        run: ./tools/build/junit_summary.py --path-to-test-results "build/otel_unit_results/**/*.xml" --header "Test summary for PHP ${PHP_VERSION}" >>$GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-otel-unit-${{ matrix.php-version }}
          path: |
            build/otel_unit_results/*
